aws-samples/eks-workshop

- .github/CODEOWNERS
List codeowners for some protected files in the repo, to prevent malicious editing.
> Protected files

- static/css/theme-mine.css
> Update theme-mine.css to add styling for tabs

- content/scaling/cleanup.md
> Update cleanup scripts

- content/scaling/deploy_ca.md
points scaling scection files to the master branch site path.
> update file links to point to master branch

- content/introduction/architecture/cluster_setup_options.md
- content/scaling/deploy_ca.md
Add kubeadm to the list of tools.
> adding kubeadm

- content/conclusion/_index.md
It currently says "What have we accomplished" and lists... nothing. Which isn't true!
> Should probably say 'conclusion'

- package.json
Adds a theme script, and changes the port to 8080 (to support c9 dev environment)
> updating to support cloud9 dev environment

- content/codepipeline/role.md
- content/monitoring/deploy-grafana.md
#81 and #102 
Fixes these issues.
> closes #81 and #102

- content/logging/_index.md
ElasticSearch => Elasticsearch
> Update Elasticsearch name to fit correct case

- content/monitoring/deploy-grafana.md
Error in `ELB=...` command and wrong Grafana service type
Fixed error in `ELB=...` command and `service\grafana` service type (`LoadBalancer`)
> fix ELB variable command and wrong service type in output

- content/helm/using.md
remove extra step from workflow
> Remove Namespace reference in steps

- content/monitoring/prereqs.md
> Fix for #66

- layouts/partials/footer.html
- package.json
#120 
Fixes the JS console error @geremyCohen found.
> Fix js exception

- content/scaling/deploy_ca.md
> Fix typo in cluster_autoscaler filename

- content/logging/configurecwl.md
- content/logging/deploy.md
removing region from urls, and removing the warning about default region where applicable. (leaving it for the fluentd.yml file for now)
> removing region from urls

- content/logging/cleanup.md
currently, following the instructions, you're in a directory that you try to delete.
> cd out of the directory you're about to delete

- content/calico/stars_policy_demo/apply_network_policies.md
- content/calico/stars_policy_demo/create_resources.md
- content/calico/stars_policy_demo/default_policy.md
- content/calico/stars_policy_demo/directional_traffic.md
adding wgets for the yaml files.
> adding wgets for the yaml files

- layouts/shortcodes/cf-launch.html
NA
Fixe to the CFN template shortcode to deal with quirks in old/new console.
> Fix for CFN shortcode link

- content/eksctl/launcheks.md
- content/prerequisites/workspaceiam.md
Add warnings about validating the IAM role in the Cloud9 IDE
> Add warnings about validating the IAM role in the Cloud9 IDE

- content/helm_root/helm_micro/customize.md
Fix bug where tests folder was not removed.
> Update the Helm Chart Module

- content/scaling/deploy_hpa.md
Fixes #205 
Update metrics-server chart to v2.0.4 (updating metrics-server image to v0.3.1
> Update metrics-server chart to v2.0.4 (Fixes #205)

- content/calico/_index.md
> Fix small typo

- content/prerequisites/k8stools.md
> update kubectl download link to version 11.5

- content/eksctl/test.md
Fixes #257 
Fixed a typo in the command to export the role name
> Update Role Name Export

- content/dashboard/connect.md
The preview option is actually under Tools. I just added "tools"
N/A
The preview option is actually under Tools. I just added "tools"
> Updated directions for cloud9 menu option

- content/healthchecks/livenessprobe.md
Add full path as location to save file, eliminates potential confusion.
> Add -p flag when creating directory.

- content/cleanup/workspace.md
> Removed the reference to the EC2 instance key-pair

- content/monitoring/deploy-prometheus.md
> Correcting typo

- content/introduction/architecture/cluster_setup_options.md
> Add Kubernetes in Docker option

- content/batch/artifact.md
- content/batch/cleanup.md
- content/logging/cleanup.md
- content/logging/prereqs.md
- content/prerequisites/workspaceiam.md
- content/scaling/cleanup.md
- content/scaling/deploy_ca.md
- content/spotworkers/workers.md
> Enclose jq argument in all commands, some interpreters fail to execute

- content/cleanup/undeploy.md
The file is missing on master so at-least point to the same one as the URL that is used in the docs for bringing up this dashboard.
> The old URL gives a 404.

- content/servicemesh_with_appmesh/_index.md
Updated aws app mesh general availability
> updated aws app mesh general availability

- content/servicemesh_with_appmesh/_index.md
- content/servicemesh_with_appmesh/cleanup.md
- content/servicemesh_with_appmesh/components.md
- content/servicemesh_with_appmesh/create_k8s_app.md
- content/servicemesh_with_appmesh/create_mesh.md
- content/servicemesh_with_appmesh/create_virtual_nodes.md
- content/servicemesh_with_appmesh/create_virtual_routers.md
- content/servicemesh_with_appmesh/testing_the_app_mesh.md
> disabling app mesh until it's rewritten

- content/servicemesh_with_appmesh/create_virtual_nodes.md
Fixing backend attribute of virtual node creation
> Fixing backend attribute of virtual node creation

- content/eksctl/_index.md
> Update eksctl index md

- content/introduction/basics/concepts_nodes.md
Move point at the end of the sentence to the end of the sentence.
> Move dot to end.

- content/eksctl/test.md
This will allow compatibility for existing Instance Profile usage with AWS Events
> Added Instance Profile ARN to bash exports

- content/batch/_index.md
- content/spotworkers/_index.md
- content/spotworkers/cleanup.md
- content/spotworkers/deployhandler.md
- content/spotworkers/preferspot.md
- content/spotworkers/workers.md
- content/x-ray/_index.md
- templates/amazon-eks-nodegroup-with-mixed-instances.yml
remove instance profile creation from Spot Worker CFN. Updated steps to reference existing ARN support. This should now support AWS Event automation
> Updated Spot Module with Inst Prof ARN for EE Support

- content/codepipeline/_index.md
- content/codepipeline/change.md
- content/codepipeline/cleanup.md
- content/codepipeline/codepipeline.md
- content/codepipeline/configmap.md
- content/codepipeline/forksample.md
- content/codepipeline/githubcredentials.md
- content/codepipeline/role.md
bring back cicd, but with a warning for EE accounts.
> adding back cicd, but with a warning for EE accounts

- content/network-policies/tigera/tsce-cw-integration.md
> fix image paths

- content/jenkins/_index.md
moving jenkins to follow code* chapter
> moving jenkins to follow code* chapter

- content/prerequisites/k8stools.md
> update kubectl version

- content/custom_resource_definition/_index.md
Fixing small typo on the title
> Typo on the title

- content/eksctl/test.md
> updating commands to get/store instance profile arn and role name

- content/x-ray/cleanup.md
> include detaching role policy

- config.toml
- package-lock.json
- package.json
> updating packages

- layouts/partials/footer.html
> fix modernizr js reference

- content/eksctl/launcheks.files/eksworkshop.yml.template
- content/eksctl/launcheks.md
- content/prerequisites/k8stools.md
> updating to 1.13

- content/advanced-networking/secondary_cidr/configure-cni.md
> Update sample VPC CNI version

- layouts/partials/menu-footer.html
> updating year

- content/dashboard/connect.md
- content/eksctl/test.md
- content/healthchecks/_index.md
- content/healthchecks/cleanup.md
- content/healthchecks/livenessprobe.md
- content/healthchecks/readinessprobe.md
*Issue #, if available:* n/a
Standardizing some punctuation
Fixing some typos
Clarifying some unclear sentences
> Fixing some typos and rewording/clarifying sentences

- content/servicemesh_with_appmesh/create_the_k8s_app/prereqs.md
https://github.com/aws-samples/eks-workshop/issues/354
Add prereqs chapter.
> Added a prereqs chapter.

- content/eksctl/launcheks.md
- content/eksctl/test.md
removing error language for eksctl, since eksctl now doesn't error.
> Iam auth error statements

- package-lock.json
> updating npms to close a security issue

- content/servicemesh_with_appmesh/create_the_k8s_app/set_perms.md
https://github.com/aws-samples/eks-workshop/issues/332
Make env var dependencies more explicit by first verifying they exist.
> Adding checks for ROLE and REGION vars.

- content/intro_to_rbac/_index.md
- content/intro_to_rbac/cleanup.md
- content/intro_to_rbac/create_iam_user.md
- content/intro_to_rbac/create_role_and_binding.md
- content/intro_to_rbac/install_test_pods.md
- content/intro_to_rbac/intro.md
- content/intro_to_rbac/map_iam_user_to_k8s_user.md
- content/intro_to_rbac/test_rbac_user_without_roles.md
- content/intro_to_rbac/verify_user_role_binding.md
https://github.com/aws-samples/eks-workshop/issues/389
> Add Rbac chapter

- content/eksctl/prerequisites.md
> pinning eksctl while they fix a bug in nodegroup output

- layouts/partials/footer.html
> removing html5 shiv to follow upstream theme

- content/prerequisites/self_paced/iamrole.md
> clarifying steps

- content/eksctl/prerequisites.md
> downloading the latest version always

- content/weave_flux/prereqs.md
> updating for new blueprint

- content/kubeflow/install.md
- content/kubeflow/jupyter.md
- content/weave_flux/installweaveflux.md
> updating links

- content/eksctl/launcheks.md
- content/kubeflow/install.md
> fixed kf links

- content/weave_flux/codepipeline.md
- content/weave_flux/deploymentmanifests.md
- content/weave_flux/installweaveflux.md
- content/weave_flux/prereqs.md
*Issue #, if available:* NA, minor doc tweaks based on running through the module.
*Description of changes:* Minor doc tweaks.
> Minor doc enhancements to GitOps module

- content/kubeflow/cleanup.md
- content/kubeflow/dashboard.md
- content/kubeflow/install.md
Address bugs from Issue #462  
Fixed some bugs and updated instructions to latest Kubeflow version
https://www.kubeflow.org/docs/aws/troubleshooting-aws/
> Fixed some bugs and updated instructions to latest Kubeflow version

- content/kubeflow/install.md
Fixing https://github.com/aws-samples/eks-workshop/issues/479
> using the 0.7 release, changing the sequence of sed statements

- content/kubeflow/cleanup.md
- content/kubeflow/install.md
- content/kubeflow/training.md
*Issue #, if available:*https://github.com/aws-samples/eks-workshop/issues/508
*Description of changes:* Addresses https://github.com/aws-samples/eks-workshop/issues/508
> Increase ng for kubeflow chapters

- content/kubeflow/kubeflow.files/mnist-inference.yaml
*This fixes Issue #510*
* Added a deployment selector so that kubectl successfully validates the manifest
* Removed dependency on a GPU for pod scheduling
> Make Model Inference module pass

- content/kubeflow/install.md
Use `jq` to extract the nodegroup name from `eksctl` to reduce the chance of error made by the student.
> Update kubeflow nodegroup size change instructions

- content/kubeflow/distributed.md
> Add distriuted training section for kubeflow workshop

- content/eksctl/test.md
> Why is this caps? duh

- content/appmesh/port_to_app_mesh/testing_app_mesh_v1.md
`dj` pod should contain the proxy container now. Count should be at 2/2.
> Fix dj pod container status

- content/appmesh/port_to_app_mesh/canary_testing.md
`jazz` service traffic is split 90/10 between v1 and v2.
> Fix jazz service traffic split

- content/advanced/420_kubeflow/_index.md
- content/advanced/420_kubeflow/pipelines.md
*Description of changes:* minor changes to kubeflow index page
> minor changes to kubeflow index page

- content/020_prerequisites/workspace.md
- layouts/partials/custom-header.html
- package-lock.json
- package.json
*Issue #, if available:*https://github.com/aws-samples/eks-workshop/issues/539
*Description of changes:*changing cloud9 to t2.small
> changing cloud9 to t2.small

- content/advanced/420_kubeflow/training.md
*Description of changes:*minor changes to training
> minor changes to training

- content/advanced/420_kubeflow/inference.md
- content/advanced/420_kubeflow/install.md
- content/advanced/420_kubeflow/training.md
*Issue #, if available:*https://github.com/aws-samples/eks-workshop/issues/537
*Description of changes:*fix intermittent issue with sed command
> fix intermittent issue with sed command

- content/010_introduction/_index.md
- content/020_prerequisites/_index.md
- content/030_eksctl/_index.md
- content/advanced/410_batch/_index.md
- content/beginner/040_dashboard/_index.md
- content/beginner/050_deploy/_index.md
- content/beginner/060_helm/_index.md
- content/beginner/070_healthchecks/_index.md
- content/beginner/080_scaling/_index.md
- content/beginner/090_rbac/_index.md
- content/beginner/110_irsa/_index.md
- content/beginner/130_exposing-service/_index.md
- content/beginner/140_assigning_pods/_index.md
- content/beginner/150_spotworkers/_index.md
- content/beginner/170_statefulset/_index.md
- content/intermediate/220_codepipeline/_index.md
- content/intermediate/230_logging/_index.md
- content/intermediate/240_monitoring/_index.md
- content/intermediate/245_x-ray/_index.md
- content/intermediate/250_cloudwatch_container_insights/_index.md
> adding CON tags

- content/020_prerequisites/_index.md
- content/030_eksctl/_index.md
- content/advanced/420_kubeflow/_index.md
> adding OPN401 tags

- content/030_eksctl/launcheks.md
swap to using managed nodes for the default nodegroup.
> launch using managed nodes

- config.toml
> linking to other workshops

- content/advanced/420_kubeflow/inference.md
- content/advanced/420_kubeflow/training.md
https://github.com/aws-samples/eks-workshop/issues/565
> fixes for inference

- content/020_prerequisites/k8stools.md
- content/030_eksctl/prerequisites.md
- content/beginner/060_helm/helm_intro/install.md
> fix bash-completion activation

- content/020_prerequisites/k8stools.md
- content/030_eksctl/prerequisites.md
- content/beginner/060_helm/helm_intro/install.md
> fix one more bug in completion

- content/beginner/060_helm/helm_nginx/cleaningup.md
Correcting label selector for helm-based deployment of nginx.
> Fixing another occurrence of the wrong pod label

- content/advanced/420_kubeflow/pipelines.md
*Description of changes:*fixing minor bug in jq
> Pipeline patch

- content/beginner/110_irsa/deploy.files/iam-pod.yaml
*Issue #, if available:* https://github.com/aws-samples/eks-workshop/issues/581
> fixing issue# 581

- content/advanced/420_kubeflow/install.md
- content/advanced/420_kubeflow/pipelines.md
*Issue #, if available:*https://github.com/aws-samples/eks-workshop/issues/576
*Description of changes:* added sagemaker:InvokeEndpoint IAM permissions that was missing, fixed jq error
> minor change to iam permissions in pipelines chapter

- content/intermediate/250_cloudwatch_container_insights/accesswp.md
- content/intermediate/250_cloudwatch_container_insights/installwordpress.md
- content/intermediate/250_cloudwatch_container_insights/wraup.md
**Important fixes:**
- Force the name of the helm release
- Fix a code error to get the WP admin password
**Minor fixes:**
- Typos
- Formatting
> Container inside fix

- content/intermediate/260_weave_flux/codepipeline.md
N/A
Updated the path for the Dockerfile.
> Wrong path for the Dockerfile. Updated it to reflect recent changes.

- content/beginner/110_irsa/deploy.files/iam-pod.yaml
- content/beginner/110_irsa/oidc-provider.md
- add a `selector` section to iam-pod.yaml 
- replace `--name` (deprecated) by `--cluster` to be future proof and to avoid unnecessary warning
> Iam role service accounts

- content/beginner/060_helm/helm_micro/rolling_back.md
helm status  does not work user has to issue this command instead helm status workshop, and helm history command does not work user has to issue helm history workshop command
> Clearer directions for helm status

- content/advanced/420_kubeflow/training.md
Provide persisted model to unblock inference if user meet problem in training chapter. 
> Provide persisted model to unblock inference

- content/beginner/130_exposing-service/ingress_controller_alb.md
added more guidance on the flag that needs to be update for alb-ingress-controller.yaml
> Update cluster name instruction made more clear

- content/020_prerequisites/workspaceiam.md
*Description of changes:*customizing region for reInvent
> customizing region for reInvent

- content/intermediate/230_logging/setup_es.md
> Updated instance type from M4 to M5

- content/advanced/310_servicemesh_with_istio/deploy.md
- content/advanced/310_servicemesh_with_istio/install.md
- content/advanced/320_servicemesh_with_appmesh/create_app_mesh_components/adding_crds.md
- content/advanced/320_servicemesh_with_appmesh/create_app_mesh_components/create_injector_controller.md
- content/advanced/320_servicemesh_with_appmesh/create_app_mesh_components/set_injector_criteria.md
- content/advanced/320_servicemesh_with_appmesh/create_the_k8s_app/create_the_app.md
- content/advanced/320_servicemesh_with_appmesh/create_the_k8s_app/test_the_app.md
- content/advanced/320_servicemesh_with_appmesh/create_the_k8s_app/test_worker_perms.md
- content/advanced/320_servicemesh_with_appmesh/port_to_app_mesh/canary_testing.md
- content/advanced/320_servicemesh_with_appmesh/port_to_app_mesh/create_the_mesh.md
- content/advanced/320_servicemesh_with_appmesh/port_to_app_mesh/create_the_virtual_nodes.md
- content/advanced/320_servicemesh_with_appmesh/port_to_app_mesh/create_the_virtual_services.md
- content/advanced/320_servicemesh_with_appmesh/port_to_app_mesh/testing_app_mesh_v1.md
- content/advanced/320_servicemesh_with_appmesh/port_to_app_mesh/testing_the_v2.md
- content/advanced/320_servicemesh_with_appmesh/port_to_app_mesh/triggering_injector_first_time.md
- content/advanced/410_batch/artifact.md
- content/advanced/410_batch/dashboard.md
- content/advanced/410_batch/deploy.md
- content/advanced/410_batch/jobs.md
- content/advanced/410_batch/workflow-advanced.md
- content/advanced/410_batch/workflow-simple.md
- content/advanced/420_kubeflow/inference.md
- content/advanced/420_kubeflow/install.md
- content/advanced/420_kubeflow/pipelines.md
Updating output boxes in the advanced section
> Reswizzle output boxes

- content/beginner/080_scaling/deploy_ca.md
Pointing out the aws region change as it is easy to oversee
Pointing out the aws region change as it is easy to oversee
> Bold aws_region

- content/intermediate/260_weave_flux/installweaveflux.md
Its too easy to miss the substitution for YOURUSER, so I would suggest we make this into an environment variable, and reuse.
> changing YOURUSER to env var

- content/intermediate/260_weave_flux/deploymentmanifests.md
related to https://github.com/aws-samples/eks-workshop/pull/635
> YOURUSER env var

- content/020_prerequisites/workspaceiam.md
Clarify instructions for opening preferences tab
> Clarify instructions for opening preferences tab

- content/beginner/120_network-policies/tigera/tsce-sg-integration.md
Made edits to the installing the webserver part to make reading the code a lot easier
> Add code blocks to make code more readable

- content/beginner/120_network-policies/calico/install_calico.md
Signed-off-by: Michael Hausenblas <hausenbl@amazon.com>
> updates Calico install to VPC CNI 1.6

- content/beginner/060_helm/_index.md
- content/beginner/060_helm/helm_intro/_index.md
- content/beginner/060_helm/helm_intro/install.md
- content/beginner/060_helm/helm_micro/_index.md
- content/beginner/060_helm/helm_micro/customize.md
- content/beginner/060_helm/helm_micro/deploy.md
- content/beginner/060_helm/helm_micro/rolling_back.md
- content/beginner/060_helm/helm_micro/service.md
- content/beginner/060_helm/helm_nginx/_index.md
- content/beginner/060_helm/helm_nginx/cleaningup.md
- content/beginner/060_helm/helm_nginx/searchchart.md
* added a notice with the v2tov3 official documentation
* removed duplicate command
* added missing information for `serviceaccount.yaml`
* added multiple cosmetic changes based on makrdownlint feedback
> Helm V3 fixes

- content/beginner/080_scaling/deploy_hpa.md
> fixed the helm install command

- content/030_eksctl/prerequisites.md
* Updated the URL to get the latest version of `eksctl`
> update eksctl url

- content/beginner/090_rbac/cleanup.md
#392
Update cleanup section:
* Added info to delete the `rbacuser-role-binding.yaml` 
> add missing rm from rbac cleanup

- content/030_eksctl/prerequisites.md
- content/920_cleanup/eksctl.md
- content/intermediate/250_cloudwatch_container_insights/wraup.md
#425 
* Added more information on `eksctl cluster delete` behavior.
> Add more information on eksctl cluster delete

- content/beginner/190_efs/deploying-provisioner.md
- content/beginner/190_efs/deploying-services.md
- content/beginner/190_efs/efs-provisioner.md
- content/beginner/190_efs/launching-efs.md
Minor edit
Thanks for making this go live!
I worked through the module from eksworkshop.com just to do one more round of testing and made a few textual changes for better readability of the instructions. None of the commands were modified and any added. 
> Minor text changes to instructions

- content/beginner/060_helm/helm_intro/_index.md
Now that tiller is not needed anymore, we do not install any component on EKS
And so I replace the intro title.
> update the title for helm

- content/beginner/080_scaling/deploy_hpa.md
Changed helm install for metrics-server to make compatible with Helm3. 
> Changed helm command in HPA to helm3 compatible

- content/020_prerequisites/workspaceiam.md
*Description of changes:* I thought it could be useful to simplify the IAM role validation process to a single command attendees can execute. Feel free to disregard this PR if this is not desired.
> Simplifies IAM role validation

- content/advanced/420_kubeflow/horovod.md
- content/advanced/420_kubeflow/install.md
- content/authors.md
*Issue #, if available:*https://github.com/aws-samples/eks-workshop/issues/727
- provide instructions to use Kubeflow v1.0.1
- we are using default install (not Cognito)
- we are using IAM Roles for SA feature 
> Update Kubeflow to v1.0.1

- content/beginner/040_dashboard/connect.md
- content/beginner/060_helm/helm_nginx/updatecharts.md
Missing instructions for some errors
Fix of some issues our customers came across during a workshop.
> Fixes from an EKS workshop 

- content/beginner/190_efs/launching-efs.md
Get below error with the existing command
Error parsing parameter '--filters': Second instance of key "Name" encountered for input
> Update filter command for subnets

- content/advanced/420_kubeflow/dashboard.md
*Description of changes: minor changes to previous PR
> Remove ALB endpoint for Kubeflow access due to security

- content/advanced/420_kubeflow/dashboard.md
- content/advanced/420_kubeflow/fairing.md
- content/advanced/420_kubeflow/training.md
*Issue #, if available:* NA
*Description of changes:* moved failed mnist-training data to hidden and optional 
> minor kubeflow improvements

- content/beginner/180_fargate/prerequisites.md
Fixed typo in Beginner folder for EKS with Fargate prerequisites 
> Fixed typo

- content/intermediate/280_backup-and-restore/cleanup.md
- package.json
> url-ignore edits to test config due to build fails

- content/beginner/080_scaling/deploy_hpa.md
These changes are required for my deployment of metrics-server on EKS 1.15
metrics-server needs additional helm values for EKS 1.15 (and possibly other versions)
> Fix instructions for metrics-server on EKS

- content/beginner/190_ocean/register.md
- package.json
> fixing build with some ignore-urls

- content/intermediate/240_monitoring/deploy-grafana.md
Change to enable the PVC creation. 
Tested with 5.0.18 from the stable repo.
> persistence.enabled is set to false by default

- content/advanced/310_servicemesh_with_istio/download.md
none
update istio version to 1.5.2
> bump istio version from 1.5.1 to 1.5.2

- content/advanced/420_kubeflow/fairing.md
*Issue #, if available:*User run into permissions issue with creating S3 bucket. This came through Kubeflow slack
*Description of changes:* Add instructions to add S3 permissions and assign to node role
> Adding S3 permissions into Fairing chapter

- content/beginner/040_dashboard/dashboard.md
> fixing dasboard port number

- content/beginner/180_fargate/prerequisites.md
The script to check for Fargate availability in a region had some minor formatting issues that prevented it from running successfully. I updated the script, and it works properly now.
> Fixed Fargate Availability Script

- content/beginner/091_iam-groups/create-iam-roles.md
*Description of changes:* This PR fixes a simple typo.
> Fixes typo

- content/advanced/420_kubeflow/install.md
Because the Initial document was written for solely linux user, I was in trouble. 
So I added more information for OSX user.
> For OSX user, additional information is needed

- content/beginner/200_secrets/_index.md
- Fix a duplication typo in https://eksworkshop.com/beginner/200_secrets/
> Fix a typo in SealedSecret index

- content/010_introduction/architecture/cluster_setup_options.md
> Update kubeadm link

- content/intermediate/290_argocd/cleanup.md
While browsing the docs, I noticed these extra lines from what I assume was an incomplete conflict resolution.
> docs: remove extra lines from incomplete conflict resolution

- content/beginner/180_fargate/ingress.md
Not available.
A small fix for spelling and grammar in the Fargate chapter.
> Fix Fargate spelling

- content/020_prerequisites/k8stools.md
- content/beginner/091_iam-groups/test-cluster-access.md
In some cases the file end-up empty as we read and write in the same file at the same time.
This update solves the problem
> Fix problem while updating kubeconfig files

- content/intermediate/290_argocd/configure.md
Just a small fix to ensure the next command can use the environment variable.
> fix(bash): export variable

- README.md
> Testing pr settings

- content/beginner/110_irsa/iam-role-for-sa-2.md
> fix: grammatical error

- content/beginner/120_network-policies/tigera/_index.md
> Updates to the title page.

- content/beginner/120_network-policies/tigera/register.md
> Update Calico Enterprise trial.

- content/beginner/120_network-policies/_index.md
will upload the Calico Enterprise image.
> Update N/w policies page.

- content/beginner/120_network-policies/tigera/_index.md
Removed extra spaces in the formatting.
> Fix on format.

- content/beginner/120_network-policies/tigera/_index.md
Sorry for extra work - having issues with my laptop git.
> Fix Missing '['

- content/beginner/120_network-policies/_index.md
> fix extra spaces.

- content/beginner/091_iam-groups/test-cluster-access.md
According to the context, "Switching" should be the correct word.
> Fix typo in slide

- content/intermediate/290_argocd/_index.md
correct misspelling: Deployement -> Deployment
> docs(_index.md): correct misspelling: Deployement

- content/010_introduction/_index.md
- content/020_prerequisites/_index.md
- content/beginner/060_helm/_index.md
- content/beginner/190_efs/_index.md
> adding video links

- content/beginner/090_rbac/map_iam_user_to_k8s_user.md
Fixing grammar from it's to its
> Fix grammar

- content/beginner/091_iam-groups/create-iam-roles.md
> IAM RBAC - Fix typo in docs

- content/beginner/040_dashboard/cleanup.md
- content/beginner/040_dashboard/connect.md
- content/beginner/040_dashboard/dashboard.md
* create a cleanup page
* set the dashboard version as an env. variable
> Update Kubernetes Dashboard lab

- content/beginner/091_iam-groups/_index.md
- content/beginner/091_iam-groups/cleanup.md
- content/beginner/091_iam-groups/configure-aws-auth.md
- content/beginner/091_iam-groups/create-iam-groups.md
- content/beginner/091_iam-groups/create-iam-roles.md
- content/beginner/091_iam-groups/create-k8s-rbac.md
- content/beginner/091_iam-groups/create_iam_users.md
- content/beginner/091_iam-groups/intro.md
- content/beginner/091_iam-groups/test-cluster-access.md
* add command to create the ~/.aws folder if missing
* update cleanup
* make commands more readable
* markdown linter best practices
* remove the command to generate the`ACCOUNT_ID` (it is already set in
`~/.bash_profile`)
* fix typos
> update IAM group lab

- content/010_introduction/_index.md
- content/020_prerequisites/_index.md
> updating video links for intro and prereq chapters

- content/beginner/130_exposing-service/accessing.md
Remove dupe line in the sample output of nslookup
> Fix sample output of nslookup

- content/020_prerequisites/k8stools.md
- content/030_eksctl/_index.md
- content/030_eksctl/launcheks.md
The official AWS doc recommends 1.17:
* Update kubectl download link
* fix kubernetes version in the eksctl YAML file.
> Update EKS cluster version to 1.17

- content/intermediate/230_logging/cleanup.md
- content/intermediate/230_logging/config_es.md
- content/intermediate/230_logging/deploy.files/fluentbit.yaml
- content/intermediate/230_logging/prereqs.md
#879 
* IRSA:Revert IAM policy. It was overwritten by another one by mistake during my last PR
* clean_up: remove typo
* clean_up: added unset ES_ENDPOINT
*ES: added ES_ENDPOINT
* Fluentbit: added recommended parameters to the `configmap`
> Fix logging lab

- content/advanced/420_kubeflow/inference.md
- content/advanced/420_kubeflow/install.md
- fixed minor bug with scaling node group
- added cleanup instructions for model training and inference
> minor improvements to kubeflow chapters

- config.toml
- content/030_eksctl/launcheks.md
- content/_index.md
- content/advanced/420_kubeflow/fairing.md
- content/advanced/420_kubeflow/jupyter.md
- content/intermediate/250_cloudwatch_container_insights/_index.md
- content/intermediate/250_cloudwatch_container_insights/wraup.md
- content/more_resources.md
> adding crosslinks

- content/beginner/090_rbac/create_iam_user.md
- content/beginner/090_rbac/create_role_and_binding.md
- content/beginner/090_rbac/test_rbac_user_without_roles.md
- content/beginner/130_exposing-service/accessing.md
* Update variable with underscores to inline code instead of italic
* Indent some JSON outputs to match 4 space indent from other lessons
> Formatting tweaks

- content/beginner/091_iam-groups/create-iam-roles.md
- content/beginner/091_iam-groups/test-cluster-access.md
*Issue #, if available:* n/a
Spelling and other cosmetic changes in `beginner/091_iam-groups/`.
> Spelling and other cosmetic changes (beginner/091_iam-groups)

- content/advanced/320_servicemesh_with_appmesh/deploy_dj_app/test_the_app.md
This is the Fix to correct the Typo Error on the Test the DJ App on App Mesh Integration which is part of the Advanced Labs.
> ServiceMesh-TEST-DJ-APP-FIX

- content/intermediate/260_weave_flux/deploymenthelm.md
#906 
I updated the nginx chart version to a more recent one due to errors related to the Deployment API version observed in the helm operator logs.
> Updated nginx chart version helm exercise

- content/beginner/080_scaling/deploy_hpa.md
Warning linked to non-existent page
Changed link path and removed text based edit tracking
> Fix broken link on HPA configuration page

- content/intermediate/230_logging/prereqs.md
*Issue #, if available:* n/a
Fix formatting in "Configure IRSA for Fluent Bit" page, by removing superfluous opening brace from opening note.
> Remove superfluous opening brace

- content/020_prerequisites/ec2instance.md
Updated ec2instance.md to work with the new EC2 console UI
Changed the deep link to find Cloud9 instance to work with the new EC2 console UI 
> New EC2 console UI

- content/beginner/140_assigning_pods/affinity.md
- content/beginner/140_assigning_pods/affinity_usecases.md
- content/beginner/140_assigning_pods/cleaning.md
- content/beginner/140_assigning_pods/node_selector.md
#933 
* remove beta notice
*  Formatting cleanup based on Hugo linter
> Affinity-Anti affinity remove beta notice

- package-lock.json
- package.json
> dependabot sec fix: bl package update

- content/advanced/420_kubeflow/install.md
Home directory can vary, so let's make it universal.
> Make script homedir agnostic

- content/intermediate/310_open_policy_agent/policy-example-1.md
Use correct file name as input for configmap creation (L48/L63)
> fix: OPA example file name

- content/beginner/190_efs/efs-csi-driver.md
Replace mistaken written efs-pv.yaml by efs-pvc.yaml.
I retrieved the good name on the cleanup part.
> Replace efs-pv.yaml by efs-pvc.yaml

- content/advanced/320_servicemesh_with_appmesh/install_app_mesh_controller/install_controller.md
Update the controller name and latest list of CRD's to avoid confusion.
> update outputs in 320, install controller section

- content/beginner/090_rbac/create_iam_user.md
Fixed the typo error
Fixed the typo error
> Fixed the typo error

- content/beginner/190_fsx_lustre/_index.md
- content/beginner/190_fsx_lustre/cleaning.md
- content/beginner/190_fsx_lustre/deploying-services.md
- content/beginner/190_fsx_lustre/launching-fsx.md
> New module for FSx Lustre setup and PVC test

- content/beginner/190_efs/efs.files/efs-pvc.yaml
Fix typo in yaml file `efs-pvc.yaml`
> fix typo in efs-pvc.yaml

- content/beginner/091_iam-groups/configure-aws-auth.md
NA
Fix typo in "In order to gives access to the IAM Roles..." to "In order to give access to the IAM Roles..."
> Update typo in configure-aws-auth.md

- content/advanced/320_servicemesh_with_appmesh/port_to_app_mesh/mesh_resources_overview.md
Small push but... "Insist on the Highest Standards" right  :) ?
> Missing letter (typo)

- content/advanced/310_servicemesh_with_istio/deploy.md
> Fix small wording

- content/intermediate/240_monitoring/_index.md
- content/intermediate/240_monitoring/cleanup.md
- content/intermediate/240_monitoring/deploy-grafana.md
- content/intermediate/240_monitoring/deploy-prometheus.md
- content/intermediate/240_monitoring/prereqs.md
#78 
* Update helm repo
* Update helm installation doc
* create ns before using helm
* update clean up
* add some information on grafana and prometheus at the beginning of the
lab
* Update cleanup
> Update Prometheus and Grafana lab

- content/beginner/170_statefulset/ebs_csi_driver.md
Fixed the policy file name and the variable name for policy arn which incorrectly contained CNI instead of CSI.
> Fixed confusing filenames

- content/beginner/140_assigning_pods/affinity.md
- content/beginner/140_assigning_pods/affinity_usecases.md
- content/beginner/140_assigning_pods/cleaning.md
- content/beginner/140_assigning_pods/node_selector.md
- package-lock.json
- package.json
#977
* Replace hard coded node name with variable
* update documentation for clarity
> Node selector fix

- content/beginner/091_iam-groups/test-cluster-access.md
Updating yq commands to work with v4. Alternatively could install v3 of yq instead of the latest version.
> Updating yq command

- content/beginner/091_iam-groups/test-cluster-access.md
Seperated command and result, which would make users to follow workshop document easily.
> Seperated command and result.

- content/beginner/160_advanced-networking/secondary_cidr/prerequisites.md
Using native aws-cli commands with "--query" and "--output" instead of jq. Tested and working.
> Update prerequisites.md with --query

- content/beginner/120_network-policies/calico-enterprise/register.md
> adding new Calico Enterprise Trial workflow

- content/beginner/115_sg-per-pod/90_cleanup.md
Absolutely minor (yet irritating) typo.
> Correct minor typo.

- content/intermediate/310_opa_gatekeeper/setup.md
> Add namespace parameter which is required for viewing logs

- content/intermediate/230_logging/config_es.md
Fixes #1070 
Adapt the jq statement to accept the new response type.
> Fix jq statement for ElasticSearch logging config

- content/intermediate/310_opa_gatekeeper/cleanup.md
- content/intermediate/310_opa_gatekeeper/policy-example-1.md
- content/intermediate/310_opa_gatekeeper/setup.md
fixes #1039 
Put Output into different code box
> [Issue-1039] Put Output into different code box

- content/advanced/330_servicemesh_using_appmesh/add_nodegroup_fargate/_index.md
Update line 23 of content/advanced/330_servicemesh_using_appmesh/add_nodegroup_fargate/_index.md and fix spelling of 'instnace' to instance"
> Update AppMesh Docs spelling

- content/beginner/091_iam-groups/test-cluster-access.md
As users point me out, there can be different yq implementation, I just add a node to a page explaining difference in syntax for the version 4 and 3 of yq
> warn users that there can be other yq implementations

- content/intermediate/246_monitoring_amp_amg/cleanup.md
- content/intermediate/246_monitoring_amp_amg/create_amp_workspace.md
- content/intermediate/246_monitoring_amp_amg/ingest_metrics.md
- Update AMG/AMP module and delete the proxy sidecar container (not needed since prometheus release in 2.26)
- Add cleanup stage
> Update AMP/AMG module

- content/020_prerequisites/ap-southeast-1.md
- content/020_prerequisites/eu-west-1.md
- content/020_prerequisites/iamrole.md
- content/020_prerequisites/us-east-2.md
- content/020_prerequisites/us-west-2.md
- content/020_prerequisites/workspace.md
* Updated deep links for creating Cloud9 instances to include URL parameters to automatically specify instance name and instance type, reducing the amount of typing workshop attendees need to do, and the chance for human error
* Updated deep links for creating IAM role for Cloud9 instance to include URL parameter to automatically specify role name, reducing the amount of typing workshop attendees need to do, and the chance for human error
* Updated note to make use of notice formatting, and placed the note before the command it was referring to, rather than after it.
> Usability improvements

- content/beginner/110_irsa/cleanup.md
- content/beginner/110_irsa/deploy.md
*Issue #, if available: NA*
*Description of changes: Added an S3 bucket creation to the workshop so the job-s3.yaml works on a fresh account.*
> Added s3 bucket creation for 110_irsa

- content/beginner/091_iam-groups/test-cluster-access.md
cosmetic change
mkdir has idempotent-friendly flag exactly for this
> Update test-cluster-access.md - simplify mkdir

- content/advanced/430_emr_on_eks/eks_emr_using_node_selectors.md
Modifying "Using Node Selectors" documentation file
Changing the "draft: true" to "draft: false"
> Modifying "Using Node Selectors" documentation file

- content/beginner/170_statefulset/storageclass.md
*Issue #: if available* 
#1135
*Description of changes:* adding `volumeBindingMode: WaitForFirstConsumer` to EBS CSI storage class definition
> Set volumeBindingMode to EBS CSI storage class for statefulset lab

- content/intermediate/200_migrate_to_eks/create-kind-cluster.md
Fixes an issue in the migrate to eks workshop content.
> fix iptables command and add a note

- content/beginner/110_irsa/iam-role-for-sa-1.md
> Syntax error fix

- content/advanced/430_emr_on_eks/monitoring_and_logging_3.md
*Issue #1179 :*
Fixed the broken links
> Fixed issue 1179 - broken links

- content/intermediate/280_backup-and-restore/_index.md
- content/intermediate/280_backup-and-restore/backup-restore.md
- content/intermediate/280_backup-and-restore/cleanup.md
- content/intermediate/280_backup-and-restore/deploy-app.md
- content/intermediate/280_backup-and-restore/install_velero.md
- content/intermediate/280_backup-and-restore/prerequisites.md
> disable velero

- content/020_prerequisites/k8stools.md
- content/030_eksctl/launcheks.md
- content/030_eksctl/test.md
Updated k8s version to 1.19. I will update the k8s version to 1.20 when 1.21 support launches for the purposes of the upgrade lab.
> Update k8s version to 1.19. Will update to 1.20 when 1.21 launches

- content/intermediate/210_jenkins/serviceaccount.md
> Update adding the OIDC provider step warning.

- content/020_prerequisites/k8stools.md
- content/advanced/430_emr_on_eks/autoscaling.md
- content/advanced/430_emr_on_eks/cleanup.md
- content/advanced/430_emr_on_eks/eks_emr_using_node_selectors.md
- content/advanced/430_emr_on_eks/fargate_1.md
- content/advanced/430_emr_on_eks/fargate_2.md
- content/advanced/430_emr_on_eks/monitoring_and_logging_0.md
- content/advanced/430_emr_on_eks/monitoring_and_logging_3.md
- content/advanced/430_emr_on_eks/spot_instances_1.md
*Issue #, if available:* #1179, #1121, #1181
1. Updated to resolve open EMR on EKS issues listed above.
2. Tested with Kubernetes versions 1.19 and 1.20.
3. Added awscli2 install instead of awscli1 due to needed testing on item 2
4. Doc updates to revise spelling errors.
> Update EMR on EKS Chapter, validated against EKS 1.19 and 1.20

- content/intermediate/290_argocd/cleanup.md
*Issue #, if available:* 1254
Added -y to the argocd app delete command to allow it to go through properly
> Small update on lab 290

- content/beginner/140_assigning_pods/affinity.md
- content/beginner/140_assigning_pods/affinity_usecases.md
- content/beginner/140_assigning_pods/node_selector.md
tested all command with v1.20 EKS cluster
revised output using v1.20 nodes
fixed typos for clarity
> EKS v1.20 updates for 140_assigning_pods lab

- content/beginner/170_statefulset/_index.md
- content/beginner/170_statefulset/configmap.md
- content/beginner/170_statefulset/ebs_csi_driver.md
- content/beginner/170_statefulset/statefulset.md
- content/beginner/170_statefulset/storageclass.md
- content/beginner/170_statefulset/testscaling.md
Tested this for both 1.19 and 1.20
> Updated Helm chart version + cosmetic changes

- content/intermediate/245_x-ray/daemonset.files/xray-k8s-daemonset.yaml
Updating X-ray Daemon Image to Amazon Managed Image
Changing the X-ray Daemon Image to Amazon Managed X-ray Image , so that it contains all the latest fixes.
> Changing the X-ray Daemon Image to Amazon Managed X-ray Daemon Image

- content/advanced/410_batch/cleanup.md
- content/advanced/410_batch/deploy.md
- content/advanced/410_batch/install.md
- content/advanced/410_batch/jobs.md
Updated correct path for install.yaml.
Tested and updated for kubernetes 1.20
updated Argo minor version from v2.9.1 to v2.12.13.
> updated for k8s v1.20 and Argo v2.12.13

- content/020_prerequisites/clone.md
update code repositories to the official aws-containers org
> update code repositories

- content/beginner/160_advanced-networking/secondary_cidr/eniconfig_crd.md
Minor format fix to render output sections correctly.
*Description of changes:* Minor formatting fix with networking module file eniconfig_crd.md. A few sections have incorrect output element/tags and were not rendering properly in the final output. Fixed all output tags now.
> Update eniconfig_crd.md : minor formatting fix

- content/intermediate/200_migrate_to_eks/create-kind-cluster.md
> Clarifying notice

- content/010_introduction/basics/concepts_objects_details_1.md
> Updating description of DaemonSet for clarity

- content/beginner/194_secrets_manager/_index.md
Issue #, if available: N/A
Description of changes: Minor change in wording
> Minor wording change

- content/beginner/180_fargate/cleaning.md
- content/beginner/180_fargate/deploying-fargate.md
*Issue #, if available:* #1323
*Description of changes:* Change to use a pin version of the files that is compatibles with 1.19
> Use previous version of the files compatibles with 1.19

- content/advanced/330_servicemesh_using_appmesh/appmesh_installation/install_appmesh.md
Added in step to update Helm repo before installing the App Mesh controller, with sample output
> Added in step to update Helm repo

- content/advanced/330_servicemesh_using_appmesh/appmesh_installation/install_appmesh.md
> Closed another output tag

- content/advanced/330_servicemesh_using_appmesh/appmesh_installation/install_appmesh.md
Closing open {{< output >}} tag
> Closing open {{< output >}} tag

- content/beginner/085_scaling_karpenter/install_karpenter.md
> Karpenter typo fix

- content/advanced/340_appmesh_flagger/fronend_vg_setup.md
> Grammar update for Deploy the Frontend Service

- content/beginner/180_fargate/prerequisites-for-alb.md
> Updated the iam policy to v2.4.0

- content/beginner/180_fargate/cleaning.md
> Fixed error on crd deletion. Put quotes.

- content/intermediate/290_argocd/_index.md
> Fix the hyperlink to argo CD

- content/advanced/330_servicemesh_using_appmesh/port_to_app_mesh/_index.md
> Fix typo, `Faragate`->`Fargate`

- content/intermediate/240_monitoring/deploy-prometheus.md
*Description of changes:* If you try to execute for the first time, you first need to add the helm repo
> Add helm repo

- content/advanced/330_servicemesh_using_appmesh/port_to_app_mesh/testing_v1.md
> Fix typos and grammar

- content/beginner/090_rbac/create_iam_user.md
tee doesn't create folder out of the box
> Create folder for storing credentials

- content/advanced/330_servicemesh_using_appmesh/appmesh_installation/install_appmesh.md
> Fixed syntax error on page

- content/beginner/060_helm/helm_micro/customize.md
> Fix spelling

- content/advanced/340_appmesh_flagger/canary_analysis.md
- content/advanced/340_appmesh_flagger/canary_deploy.md
- content/advanced/340_appmesh_flagger/testing.md
Signed-off-by: Sebastien Allamand <sallaman@amazon.com>
This is part of updating the appmesh workshop for new k8s versions
- Tested with AppMesh controller from PR [#492](https://github.com/aws/aws-app-mesh-controller-for-k8s/pull/492)
- Tested with Kubernetes versions 1.19 and 1.20.
- Doc updates to revise spelling errors.
> updating flagger module

- content/beginner/180_fargate/deploying-fargate.md
Sample app was using older version which includes annotations that are deprecated.
> Update sample app yaml to latest version

- content/beginner/200_secrets/managing-sealing-key.md
> Update output to controller version 0.17.5

- content/beginner/300_windows/calico_windows/install_calico_node.md
https://docs.aws.amazon.com/eks/latest/userguide/install-kubectl.html
> Update kubectl version to the same version with other labs and cluster

- content/030_eksctl/launcheks.md
*Description of changes:* Update to 1.21
> Update to 1.21

- package.json
Upgrading mermaid module to 9.1.3 to reduce the amount of critical vulnerabilities
> upgrade mermaid module to 9.1.3

- content/020_prerequisites/k8stools.md
- package.json
> Kubectl 1.21

- content/beginner/185_bottlerocket/deployapp.md
- content/beginner/185_bottlerocket/launchbottlerocket.md
> Bottlerocket update

- content/intermediate/310_opa_gatekeeper/setup.md
Updated workshop content for latest version of opa/gatekeeper (310_opa_gatekeeper)
> update gatekeeper to V3.8

- content/beginner/200_secrets/installing-sealed-secrets.md
Updated to latest release of sealed secrets (0.18.0)
> updated to use latest release of sealed secrets

- content/beginner/085_scaling_karpenter/install_karpenter.md
Upgrade karpenter version to compatible with eks 1.21
> upgrade karpenter version to compatible with eks 1.21

- content/intermediate/241_pixie/using_pixie/http_data.md
* Update http_data.md
* Update http_data.md
> Update http_data.md (#1436)

- content/advanced/410_batch/artifact.md
- content/advanced/410_batch/deploy.md
- content/advanced/410_batch/workflow-simple.md
- content/intermediate/241_pixie/using_pixie/http_data.md
- Fixed minor sentence errors
- Fixed broken link
> Minor changes to Advanced Batch

- content/beginner/080_scaling/deploy_ca.files/cluster-autoscaler-autodiscover.yaml
*Description of changes:* Image isn't available on the previous path anymore.
> Fix for good location of cluster-autoscaler image

- content/beginner/160_advanced-networking/secondary_cidr/eniconfig_crd.md
- content/intermediate/201_resource_management/advanced-pod-limits.md
- content/intermediate/201_resource_management/basic-pod-limits.md
- content/intermediate/201_resource_management/pod-priority.md
- content/intermediate/201_resource_management/resource-quota.md
- content/intermediate/241_pixie/prereqs.md
Latest CNI version 1.11.support for K8s 1.21
> Krish kp patch 2

- content/beginner/085_scaling_karpenter/_index.md
- content/beginner/085_scaling_karpenter/automatic_node_provisioning.md
- content/beginner/085_scaling_karpenter/install_karpenter.md
- content/beginner/085_scaling_karpenter/set_up_the_provisioner.md
- content/beginner/085_scaling_karpenter/setup_the_environment.md
resolves #1358
Upgraded Karpenter chapters to 0.15.0.
> Karpenter_v0.16

- content/beginner/060_helm/helm_micro/customize.md
* change template to templates
> Update spelling issue for eksdemo

- content/intermediate/290_argocd/_index.md
Change the location of Argo Logo image.
> Update Argo Logo image location.

- content/beginner/190_efs/cleaning.md
- content/beginner/190_efs/efs-csi-driver.md
*Issue #, if available:* 1392
*Description of changes:* Updated the EFS CSI Driver to 1.3 and added the missing cleanup of it in the cleanup section
> Updated the EFS CSI Driver to 1.3 and added the missing cleanup of it in the cleanup section

- content/beginner/300_windows/cleanup.md
> Correct invalid Url

- layouts/partials/custom-footer.html
> Moving to new cf analytics acct

- content/beginner/160_advanced-networking/secondary_cidr/configure-cni.md
> Update cni to 1.10.1

- content/beginner/050_deploy/servicetype.md
while it is implied and easy enough to work backwards to figure out which files are being compared, I felt it was better to be more clear.
> adding clarity to which "service.yaml" we are comparing

- content/920_cleanup/undeploy.md
Found broken, I guess URL was updated
> Updating k8s dashboard undeploy URL

- content/beginner/085_scaling_karpenter/_index.md
- content/beginner/085_scaling_karpenter/cleanup_karpenter.md
- content/beginner/085_scaling_karpenter/install_karpenter.md
- content/beginner/085_scaling_karpenter/setup_the_environment.md
*Issue #, if available:* #1519 
*Description of changes:* Update karpenter to 0.20 since it's broken in the current version. Reworded a few places since the webhook and controller have been merged together in the binaries.
> Update Karpenter to 0.20

- content/intermediate/310_opa_gatekeeper/policy-example-1.md
> typo fix in the workshop notes

- CONTRIBUTING.md
- README.md
mark repo as maintenance mode to prepare for the release of the next EKS Workshop
> set repository to maintenance mode

- layouts/partials/header.html
*Description of changes:* Add a warning message about the archive status of this project.
> Override header with an archive banner on all pages

- .github/CODEOWNERS
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/inactive_issues.yaml
- README.md
Added workflows to close stale/inactive PR/issues. Wording about v2
> Added inactive issues aggressive workflows and wording to direct to v2
