aws-samples/eks-workshop

content/logging/cleanup.md, content/logging/configurecwl.md, content/logging/deploy.files/fluentd.yml, content/logging/deploy.md, content/logging/prereqs.md
#73 
- added steps to create lambda_basic_execution role. repurpose log_policy folder after renaming it to iam_policy and updating references
- fluentd.yml : mentioned in configurecwl.md that us-west-2 should be updated if a different region is picked and updated stream_name value to avoid lognameprefix issue
- Added a banner to inform that all URLs default to us-west-2 and user should select the applicable region
- updated cleanup page
=> fixed all the bugs mentioned in issue#73

content/codepipeline/codepipeline.md
NA
Add additional kubectl commands to showcase how to get the service and deployment status.
=> Commands to get deployment/service status

content/monitoring/deploy-prometheus.md
added context to help the user make sure they open prometheus-values.yaml for editing before proceeding.
=> clarity on opening prometheus-values.yaml

content/logging/setup_es.md
Update Elasticsearch name to correct case: ElasticSearch => Elasticsearch
=> Update Elasticsearch name to correct case

content/deploy/cleanup.md, content/helm/_index.md, content/helm/deploy.md, content/helm/using.md
#110 and #8 
I moved the Microservices cleanup into that section. I took workflow (test, install, update with broken image, rollback) from #110 but added steps for users to build their own chart and decoupled from external repo.
=> Update Helm Section to deploy microservices

content/monitoring/deploy-prometheus.md
Wrong service type for `prometheus-server` `ClusterIP`
Changed `prometheus-server` service type (in output) for `NodePort`
p.s.: also fixed syntax highlighting in markdown for the updated page.
=> replace ClusterIP with NodePort in output; fix syntax highlighting

content/codepipeline/codepipeline.md, layouts/shortcodes/cf-launch.html
NA
This modifies the cf-launch shortcode to accept a stack name and to use the quickcreate link to simplify CFN stack launches. So far, this is only used in the CI/CD module, so this PR does not impact other modules.
=> Simplify CFN stack creation shortcode

content/helm_root/helm_micro/customize.md
The change in #208 caused the `templates/` folder to be removed completely, now causing the `mkdir` statements on the same module to fail (since `mkdir` won't automatically create subfolders). This change is adding the `-p` flag to let `mkdir` create subfolders.
=> Update mkdir command

content/codepipeline/cleanup.md
ECR is now in an independent AWS console location
removes risk of breaking if redirect from /ecs/repositories > /ecr is removed 
=> update ECR console URL

content/spotworkers/workers.md
use to read "aaplied" and changed to "applied"
use to read "aaplied" and changed to "applied"
=> Spelling error fixed

content/prerequisites/self_paced/workspace.md
Cloud9 requires third-party-cookies. Many people might want to disable them globally. So, it is beneficial to provide a link to the documentation for the specific domains to whitelist. This will probably prevent some questions and save time searching for them every time, thus providing a better overall experience.
=> Add a third-party-cookie link

content/eksctl/test.md
If we don't use quotes it fails
```
➜  eksworkshop aws cloudformation describe-stacks | jq -r .Stacks[].StackName
zsh: no matches found: .Stacks[].StackName
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
```
=> Use quotes for jq stacks

content/healthchecks/livenessprobe.md
Just a small typo in the `--previous` flag example
=> Small typo

content/prerequisites/self_paced/ap-southeast-1.md, content/prerequisites/self_paced/workspace.md
Replaces pull request #321.
Oregon at the top, Singapore is new, and the rest lexical-sorted.
=> Cloud9 Singapore (2)

content/eksctl/launcheks.files/eksworkshop.yml.template
*Issue #355* 
https://github.com/aws-samples/eks-workshop/issues/335
Changing the apiVersion to v5
=> Change apiVersion for EKSCTL input file

content/jenkins/deploy.md
Jenkins helm chart updated 
It's called 'rbac.create' now (instead if 'rbac.install')
It's also enabled by default
Changed helm command for installing Jenkins on EKS
=> update helm install jenkins command

content/prerequisites/k8stools.md
Updated link from 
https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/master/README.md#4-set-up-kubectl-to-use-authentication-tokens-provided-by-aws-iam-authenticator-for-kubernetes
*Issue #363*
updated link from
> github.com/kubernetes-sigs/aws-iam-authenticator/cmd/aws-iam-authenticators
to 
> sigs.k8s.io/aws-iam-authenticator/cmd/aws-iam-authenticator
=> Updated IAM Authenticator install path

content/helm_root/helm_nginx/installnginx.md
Noticed while going through the workshop that clicking the `helm install` link listed here results in a redirect to https://github.com/helm/helm which I think is not what was intended by this link. This new link provides information on how to use `helm install`
=> Update helm install docs

content/exposing_service/exposing.md
The LB is only listening on 80 so the example curl command will not work as is.
=> Update curl to hit HTTP port

content/exposing_service/ingress.md
The API version used is not supported on any Kubernetes version currently available in Amazon EKS. Updating to use the `extensions/v1beta1` version that works with supported Kubernetes versions.
=> Modify Ingress API version in example

content/servicemesh_with_appmesh/create_the_k8s_app/set_perms.md
appmesh workers soon need the `appmesh:StreamAggregatedResources` permission to fetch configuration for Envoy.
aws/aws-app-mesh-roadmap/issues/80 explains more.
=> Add appmesh:StreamAggregatedResources to appmesh worker policy

content/jenkins/deploy.md
Some corporate networks filter non-standard http ports like 8080. Since all the other examples so far have used port 80 and the jenkins example works just as well with port 80 exposed I am proposing to change the helm install to use port 80 instead of the default 8080. 
Additionally during experimenting with this example I found that it took the load balancer up to 5min to put the cluster nodes in service  while kubectl already reports the load balancer as active. As such suggesting to add a comment regarding that startup time and providing a means to check on the AWS console whether the instances are in service.
=> Change exposed port to 80 and add startup time comment

content/weave_flux/cleanup.md, content/weave_flux/codepipeline.md, content/weave_flux/installweaveflux.md, content/weave_flux/prereqs.md
N/A
Weave URLs were incorrect after it recently joined the CNCF.  Updated the URL, the Dockerfile location, and simplified getting the AWS account ID. 
=> Updating URLs to reflect Weave repo changes

content/codepipeline/_index.md
CodeBuild, CodeCommit, CodePipeline, CodeDeploy, and CodeStar are supported now by the tooling for AWS account provisioning for events. 
=> removed notice warning

content/kubeflow/pipelines.md
Use jq to fill in IAM credential environment variables to reduce the
risk of user errors in copying/pasting values.
=> kubeflow/pipelines: use jq to fill in credential env vars

content/kubeflow/install.md, content/x-ray/daemonset.files/xray-k8s-daemonset.yaml
Fixed minor typo of kfctl version, it should be “0.7" rather than "0.7 RC6" at https://eksworkshop.com/kubeflow/install/ as per download URL.
=> update minor typo of kfctl version.

content/advanced/420_kubeflow/training.md
#542 
Last PR changed `echo -n` to `jq -r` which is good and make setup easier but it brought a problem and results is inconsistent with `echo -n`, we change to `jq -j` to make sure it won't print a newline at the end of output, which will give exact same result as `echo -n`. 
```
$ jq -j .AccessKey.AccessKeyId /tmp/create_output.json | base64
QUtJQVZDRFROSUxHQUdENklQUFo=
$ echo -n 'AKIAVCDTNILGAGD6IPPZ' | base64
QUtJQVZDRFROSUxHQUdENklQUFo=
```
=> Use -j to prevent jq from printing a newline

content/beginner/160_advanced-networking/secondary_cidr/prerequisites.md
Tried it, and it didn't work on zsh without the quotes.
* Just added `'` around the `jq` arguments, just like on line 17.
=> Fix to work on zsh

content/beginner/150_spotworkers/cleanup.md, content/beginner/150_spotworkers/deployhandler.md, content/beginner/150_spotworkers/preferspot.md, content/beginner/150_spotworkers/workers.md
Could be a long term fix for: https://github.com/aws-samples/eks-workshop/issues/587
**Why**
- It is easier to create and manipulate spot instance using `eksctl`  (compared to CloudFormation)
**How**
-  I updated all the pages to use `eksctl` instead of cloudformation
-  I replaced the spot interrupt handler by `aws-node-termination-handler`
=> Use EKSCTL for Spot

content/beginner/170_statefulset/testfailure.md
- remove a wait flag from a `kubectl` command that doesn't need it
=> remove a wait flag from a command that doesn't need it (minor fix)

content/beginner/080_scaling/_index.md
https://github.com/aws-samples/eks-workshop/issues/621
CA cant be used for pod scaling. Updated intro from CA github page @: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-is-cluster-autoscaler
=> updated Cluster Autoscaler (CA) documentation

content/beginner/120_network-policies/tigera/environment.md
Issue https://github.com/aws-samples/eks-workshop/issues/625
Fixing a possible typo in a security group value
=> Fixing typo in security group name for Tigera section.

content/advanced/420_kubeflow/training.md
Previous HASH could be generated with a dash at the beginning which results in an invalid bucket name (or a hash at the end which looks odd). This reduces it to just alphanumeric.
Example of previous usage which results in invalid bucket name:
```
$ export HASH=$(< /dev/urandom tr -dc a-z-0-9 | head -c6)
$ export S3_BUCKET=$HASH-eks-ml-data
$ aws s3 mb s3://$S3_BUCKET --region $AWS_REGIONmake_bucket failed: s3://-z1d0e-eks-ml-data An error occurred (InvalidBucketName) when calling the CreateBucket operation: The specified bucket is not valid.
$ echo $HASH
-z1d0e
```
=> training.md: Remove invalid bucket name possibility

content/020_prerequisites/workspace.md
t2.small is no longer offered as an instance type for Cloud9.  It's been replaced with t3.small.
=> Change t2.small to t3.small

content/beginner/090_rbac/create_iam_user.md
Issue #, if available:
Under RBAC, Create User step has a bug that will cause the Test user step to fail.
Description of changes: when setting the AWS_SECRET_ACCESS_KEY and AWS_ACCESS_KEY_ID using JQ command, without specifying the -r flag, values will have enclosing double quotes which will fail the subsequent steps in this lesson.
=> RBAC: Add raw flag to JQ command

content/beginner/150_spotworkers/deployhandler.md
Original command fails: 
````
helm install aws-node-termination-handler eks/aws-node-termination-handler \
>              --namespace kube-system \
>              --set nodeSelector.lifecycle=Ec2Spot
Error: This command needs 1 argument: chart name
````
Updated to "upgrade --install" -- as per  https://github.com/aws/aws-node-termination-handler -- and correct command format
=> Correct command to upgrade / install the handler

content/beginner/150_spotworkers/deployhandler.md
Fixed wording on Spot instance interruption. The actual description falsely gives the impression that on On-Demand instances are being interrupted, while this is the case for Spot instances only.
=> Fix wording on Spot instance interruption

content/beginner/170_statefulset/ebs_csi_driver.files/attacher-binding.yml, content/beginner/170_statefulset/ebs_csi_driver.files/deployment.yml, content/beginner/170_statefulset/ebs_csi_driver.files/kustomization.yml, content/beginner/170_statefulset/ebs_csi_driver.files/provisioner-binding.yml, content/beginner/170_statefulset/ebs_csi_driver.files/serviceaccount.yaml.tmpl, content/beginner/170_statefulset/ebs_csi_driver.md
The recent update to use IRSA for the EBS CSI driver did not work
correctly.  Updated and retested on a fresh cluster to ensure it
works properly this time.
=> Fix regression in CSI driver installation

content/beginner/160_advanced-networking/secondary_cidr/cleanup.md, content/beginner/160_advanced-networking/secondary_cidr/configure-cni.md, content/beginner/160_advanced-networking/secondary_cidr/eniconfig_crd.md, content/beginner/160_advanced-networking/secondary_cidr/prerequisites.md
"Using secondary CIDR in EKS" section refers to cluster instance tags with tag key "Name" while this tag is nonexistent. Query filters based on this tag do not return any result.
Changed the queries to use other tags which are configured initially during the deployment of the cluster.
=> Correction of cluster tag use in the secondary CIDR section

config.toml, content/intermediate/250_cloudwatch_container_insights/cwcinstall.md, content/intermediate/260_weave_flux/codepipeline.md, content/intermediate/260_weave_flux/installweaveflux.md
Fixes in the Flux section of the workshop:
-  Replace old version of hard-coded flux release with a placeholder for the latest official version.
- Remove "check the acknowledge box" instruction from as there is no "acknowledge box" to check in the new Stack creation screen.
- Clicking Next on the Cleanup page in Flux section will route you to the index.html of flux "Hello World" demo app, instead of moving to the next section in the Workshop. This is because Hugo will forward requests to all index files present in the workshop directories. In order to rectify this behavior we need to give Hugo a directive to ignore app files and not render them as part of the workshop. 
By submitting this pull request, I confirm that you can use, modify, …
=> Flux section fixes

content/advanced/320_servicemesh_with_appmesh/create_app_mesh_components/about_sidecar.md
The component which automatically adds the sidecar is not AWS App Mesh Controller but AWS App Mesh Sidecar Injector.
=> Fix wrong component name

content/beginner/080_scaling/deploy_ca.files/cluster_autoscaler.yml
The following errors, for instance, are logged with the latest [cluster_autoscaler.yml](https://github.com/aws-samples/eks-workshop/blob/3c77d487689bff9aefaa621d0c5fa79c4e534b8e/content/beginner/080_scaling/deploy_ca.files/cluster_autoscaler.yml) due to the lack of k8s RBAC permissions.
```
k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:330: Failed to list *v1.Job: jobs.batch is forbidden: User "system:serviceaccount:kube-system:cluster-autoscaler" cannot list resource "jobs" in API group "batch" at the cluster scope
```
```
k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:312: Failed to list *v1.DaemonSet: daemonsets.apps is forbidden: User "system:serviceaccount:kube-system:cluster-autoscaler" cannot list resource "daemonsets" in API group "apps" at the …
```
=> Update with the latest required permissions for 1.14/1.15 cluster

content/020_prerequisites/k8stools.md, content/beginner/040_dashboard/connect.md
Added instructions for AWS CLI v2 updates in 'Start the workshop > Install Kubernetes Tools'. Cloud9 was being built using older AWS CLI version.
=> added instructions for awscliv2 + minor edits

content/beginner/080_scaling/deploy_ca.files/cluster_autoscaler.yml, content/beginner/080_scaling/test_hpa.md, content/beginner/140_assigning_pods/affinity.md
The k8s.gcr.io name is currently a facade for gcr.io/google-containers, which is only writeable by Google employees.
Changing the base url of docker images to point to the right repo.
=> changed the docker images base url

content/advanced/310_servicemesh_with_istio/download.md
istio 1.5.1 release contains bug fixes to improve robustness and fixes for the security vulnerabilities described in https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-1764
Bump version from 1.5.0 to 1.5.1
=> bump istio version to 1.5.1 due to CVE-2020-1764

content/beginner/091_iam-groups/cleanup.md
*Issue*
When tying to delete the access keys for the generated user, the secret is referenced instead of the key id, thus the delete fails and subsequently also the removal of the users.
Changed to reference key ids.
=> Fix failed delete of iam users due to wrong key id

content/beginner/090_rbac/cleanup.md
Fix failed delete-user due to existing AWS-Access-Key, when executing aws iam delete-user 
by deleting the access key first (and lastly removing the saved credentials)
=> Fix failed delete-user due to existing access key

content/beginner/180_fargate/prerequisites.md
Also, on Cloud9 using the included GNU bash 4.2, the above script threw a "[: =: unary operator expected" error, so that's fixed now as well.
=> Adding new EKS Fargate regions to warning

content/beginner/080_scaling/deploy_ca.files/cluster_autoscaler.yml, content/beginner/080_scaling/deploy_ca.md
*Description of changes:* During the deployment of the Cluster Autoscaler, we ask people to manually edit the region into the YAML manifest. However, as part of the same step, the YAML manifest is processed with `envsubst`. Since the region is already available as an environment variable [1], we can update the YAML manifest so that the region gets replaced as well when running `envsubst`.
[1] https://eksworkshop.com/020_prerequisites/workspaceiam/
=> Remove manual region configuration for Cluster Autoscaler

content/advanced/310_servicemesh_with_istio/routing.md
Prepend the correct path so that users do not receive an error when copy/pasting the last instruction to apply virtual-service-reviews-v3.yaml
When users copy/paste the last command, they receive an error because the path is not complete.
Update to the command to prepend the correct file path for the kubectl apply command.
=> Fix broken file path in Istio workshop module instructions

content/beginner/091_iam-groups/cleanup.md
*Description of changes:* I found an unnecessary dollar sign (`$`) in a cleanup command in the `Amazon EKS Workshop > Beginner > Using IAM Groups to manage Kubernetes` section [CLEANUP page](https://eksworkshop.com/beginner/091_iam-groups/cleanup/).
=> fix typo in a cleanup command on "Using IAM Groups to manage Kubernetes"

content/beginner/160_advanced-networking/secondary_cidr/configure-cni.md
CNI v1.6.1 is the latest release and default for new clusters now.
=> Update the CNI to v1.6.1

content/beginner/040_dashboard/dashboard.md
Dashboard version 1.10 generating error 404 when connecting.  Update dashboard to version 2
=> Use latest version of kubernetes dashboard

content/beginner/160_advanced-networking/secondary_cidr/configure-cni.md
To upgrade to the latest v1.6 as stated in the description, you need to apply manifest under the "v1.6" directory.
=> change the VPC CNI version in command v1.5 -> v1.6

content/beginner/090_rbac/map_iam_user_to_k8s_user.md
AS it stands the instructions will leave you unable to access the cluster with kubectl after creating the RBAC user
Get the existing configMap - which should exist as we just created the cluster.
Append the mapping for the rbac-user to the existing aws-auth configMap
And apply.
This leave the original access intact -and adds the rbac-user which I think was probably the original intent for this section
=> Get existing configMap - then apply rbac-user

content/020_prerequisites/k8stools.md, content/beginner/180_fargate/ingress.md
This changes add an annotation so that the ALB is created in IP mode.
Actually it was default to be created in instance mode and did not works on a fargate only cluster, and was not according to the following explication saying it must be using fargate ip as target which was not the case.
=> force ALB to be in IP mode for fargate

content/beginner/080_scaling/deploy_ca.files/cluster_autoscaler.yml
fixes #806 -- error in the cluster_autoscaler due to missing permission to read csi in the RBAC rules.
=> adding csinodes to CA rbac - fixes #806

content/beginner/130_exposing-service/ingress_controller_alb.md
egrep command does not work, as the name is alb-ingress-controller-xxxx, and regex invalid.
```
kubectl logs -n kube-system $(kubectl get po -n kube-system | egrep -o alb-ingress[a-zA-Z0-9-]+)
```
Simpler like this (at least it works...):
```
kubectl logs -n kube-system $(kubectl get po -n kube-system | grep alb-ingress | awk '{print $1}')
```
=> ALB ingress logs egprep command invalid

content/advanced/410_batch/cleanup.md, content/advanced/410_batch/deploy.md, content/advanced/410_batch/install.md
argo deploy with v2.1.0 fails because it uses deployments of type apps/v1beta2 which are deprecated in 1.16 ( https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/ )
update argo to first version which no longer uses these deprecated api spec
=> update argo workflow for EKS 1.16, apps/v1beta2 is deprecated as of 1.16

content/beginner/170_statefulset/ebs_csi_driver.md, content/intermediate/260_weave_flux/codepipeline.md
github master->main rename broke some download url's.
Noticed it in the weave flux section, but corrected other occurrences I found as well
=> github master->main rename broke some download url's

content/beginner/170_statefulset/ebs_csi_driver.files/deployment.yml
The previous patch file had no effect and thus the deployment was still configured to use the default ebs-csi-controller-sa service account.
=> Updating patch for ebs-csi-controller deployment

content/beginner/190_efs/launching-efs.md
previously, it fails to parse each component from the array with error: 
```
❯ for subnet in ${subnets[@]}
do
echo "creating mount target in " $subnet
aws efs create-mount-target --file-system-id $FILE_SYSTEM_ID --subnet-id $subnet --security-groups $MOUNT_TARGET_GROUP_ID
done
creating mount target in  subnet-aaa
subnet-bbb
subnet-ccc
An error occurred (ValidationException) when calling the CreateMountTarget operation: 2 validation errors detected: Value 'subnet-aaa
subnet-bbb
subnet-ccc' at 'subnetId' failed to satisfy constraint: Member must have length less than or equal to 47; Value 'subnet-aaa
subnet-bbb
subnet-ccc' at 'subnetId' failed to satisfy constraint: Member must satisfy regular expression pattern: ^subnet-[0-9a-f]{8,40}$
```
Previously, 
```
❯ echo $subnets
subnet-aaa... …
```
=> Parse subnets into array

content/intermediate/245_x-ray/cleanup.md, content/intermediate/245_x-ray/daemonset.files/Dockerfile, content/intermediate/245_x-ray/daemonset.files/build.sh, content/intermediate/245_x-ray/daemonset.files/xray-k8s-daemonset.yaml, content/intermediate/245_x-ray/role.md, content/intermediate/245_x-ray/x-ray-daemon.md
Updated the X-Ray lab to use an IAM role with a service account for the X-Ray daemonset. Changed the docker image for the X-Ray daemon to include the AWS CLI so that it can use the role ARN to access X-Ray.
=> Update X-Ray lab to use IAM roles for service accounts

content/beginner/091_iam-groups/cleanup.md, content/beginner/091_iam-groups/configure-aws-auth.md, content/beginner/091_iam-groups/create_iam_users.md, content/beginner/091_iam-groups/test-cluster-access.md
* cleanup was deleting `~/.aws` folder and so default region config was also deleted. #866 
Now, the cleanup remove both files (not the folder) and reapply the initial setup of the `.aws` folder specified [here](https://www.eksworkshop.com/020_prerequisites/workspaceiam/)
* delete duplicate instruction.
* Minor fixes based on MD linter.
=> Iam group lab  fix cleanup

content/030_eksctl/launcheks.md
During the eks workshop I have seen Brent enabling the logging from the EKS dashboard. Thought it would be better to enable it from the ClusterConfig itself.
=> Enable cloudwatch cluster logging .

content/030_eksctl/launcheks.md, content/intermediate/300_cis_eks_benchmark/_index.md, content/intermediate/300_cis_eks_benchmark/conclusion.md, content/intermediate/300_cis_eks_benchmark/debug-mode.md, content/intermediate/300_cis_eks_benchmark/intro.md, content/intermediate/300_cis_eks_benchmark/run-as-job.md, content/intermediate/300_cis_eks_benchmark/ssh-into-node.md
Added chapter 300 within the intermediate section to demonstrate the use of kube-bench to assess Kubernetes security configurations for managed and self managed nodes within Amazon EKS clusters.
=> Added chapter on Assessing CIS Amazon EKS Benchmark using kube-bench

content/intermediate/250_cloudwatch_container_insights/_index.md, content/intermediate/250_cloudwatch_container_insights/wraup.md
Added references to our newly launched One Observability workshop. This will help users to know about the exhaustive set of AWS observability features using CloudWatch and X-Ray
=> Add reference to One Observability workshop

content/advanced/420_kubeflow/fairing.md
- update custom image to "527798164940.dkr.ecr.us-west-2.amazonaws.com/tensorflow-1.15.2-notebook-cpu:1.0.0". This brings Kubeflow 1.1 features that will be merged shortly
=> updating custom image on Kubeflow Fairing chapter

content/030_eksctl/launcheks.md
I updated the cluster yaml config to always deploy nodes to AZ a, b, and c of the workshop's selected region.
As regions add more AZ's, AZ name dependencies in workshop modules (ex: Advanced VPC) may lead to the workshop module not being completed.
Also, a minor spelling update to one of the mentions of eksctl.
=> updated config yaml to use AZ a,b,c specifically

content/beginner/160_advanced-networking/secondary_cidr/configure-cni.md, content/beginner/160_advanced-networking/secondary_cidr/eniconfig_crd.md
Added information on ENIConfig label matching to simplify matching of ENIConfigs and nodes.
Also changed CNI version examples.
This change adds additional information to the secondary CIDR chapter, showing how label matching can simplify ENIConfig
=> Secondary CIDR: Added information on ENIConfig label matching

content/beginner/160_advanced-networking/secondary_cidr/cleanup.md
N/A
At the beginning of [Test Networking](https://www.eksworkshop.com/beginner/160_advanced-networking/secondary_cidr/test_networking/) the instructions to exceute `kubectl expose deployment/nginx --type=NodePort --port 80` created a Kubernetes Service. This Service is not being cleaned up
```bash
steven:~/environment $ k get all
NAME                 TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
service/kubernetes   ClusterIP   10.100.0.1     <none>        443/TCP        5d4h
service/nginx        NodePort    10.100.21.38   <none>        80:31890/TCP   9m17s
```
Added a deletion command to remove the object. 
Thanks!
=> Added deletion step for nginx Service

CONTRIBUTING.md
*Issue #, if available:* n/a
It appears that the main branch of the repository is now *main*, this change updates the corresponding contributing documentation accordingly.
=> Rename master to main in CONTRIBUTING.md

content/intermediate/310_open_policy_agent/intro.md
remove duplicate bullet points
N/A but will happily make a ticket if necessary
I removed duplicate entries of:
- Which subnets egress traffic is allowed to.
- Which clusters a workload must be deployed to.
- Which registries binaries can be downloaded from.
- Which OS capabilities a container can execute with.
- Which times of day the system can be accessed at.
=> remove duplicate bullet points in OPA guide

content/intermediate/310_open_policy_agent/policy-example-1.md
`aws ecr get-login` IS DEPRECATED using `get-login-password` instead
=> get-login-password is deprecated using get-login

content/beginner/190_efs/efs-csi-driver.md
There is not file name as efs-pv.yaml.
But we have file as efs-pvc.yaml, which points to real file - https://github.com/aws-samples/eks-workshop/blob/main/content/beginner/190_efs/efs.files/efs-pvc.yaml
Which have the code for pv, pvc, sc.
```
$ cat efs-pvc.yaml
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
name: efs-sc
provisioner: efs.csi.aws.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
name: efs-pvc
spec:
capacity:
storage: 5Gi
volumeMode: Filesystem
accessModes:
- ReadWriteMany
persistentVolumeReclaimPolicy: Retain
storageClassName: efs-sc
csi:
driver: efs.csi.aws.com
volumeHandle: fs-a29f8be3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
name: efs-storage-claim
namespace: storage
spec:
accessModes:
- ReadWriteMany
storageClassName: efs-sc …
```
=> There is not file name as efs-pv.yaml

content/beginner/190_efs/efs-csi-driver.md
EFS Container Storage Interface (CSI) points to EBS drive i.e. https://github.com/kubernetes-sigs/aws-ebs-csi-driver
With this PR, I have correct the link, which should point to https://github.com/kubernetes-sigs/aws-efs-csi-driver
=> Link is not correct

content/advanced/320_servicemesh_with_appmesh/cleanup/_index.md
An error occurred if you've created the mesh, deleted everything, and tried to recreate the mesh again, it is necessary to delete the appmesh-controller service account
Deletion of appmesh-controller service account
=> Cleanup was missing the appmesh-controller service account

content/beginner/060_helm/helm_intro/install.md, content/beginner/060_helm/helm_nginx/updatecharts.md
Old repo location https://kubernetes-charts.storage.googleapis.com/ is broken.
Updated to newer https://charts.helm.sh/stable in two .md files in the 060_helm workshop module.
=> Update location of helm stable repo to https://charts.helm.sh/stable

content/intermediate/310_open_policy_agent/policy-example-1.md
Rego policy was hard coded for us-west-2. Added AWS_REGION to the rego policy to make it work on different regions.
Added environment variable to the rego policy generation.
=> Added environment variable for Rego Policy

templates/weave_flux_pipeline.cfn.yml
Update of the default branch name for Github repo.
Updated default value for branch name.
=> Changed default branch name to main

content/intermediate/260_weave_flux/installweaveflux.md
Set default branch name to main according to the new Github default branch name.
Reference: https://github.com/fluxcd/flux/tree/master/chart/flux#configuration
=> Added default branch name to Flux

content/beginner/090_rbac/cleanup.md
Remove rbac-user from ConfigMap before deleting the aws-auth.yaml file
Forget to remove rbac-user 
Remove rbac-user from ConfigMap before deleting the aws-auth.yaml file
=> Update: remove rbac-user from ConfigMap

content/intermediate/260_weave_flux/installweaveflux.md
Since the prior "master" branch of GitHub is renamed to "main", the helm upgrade -i flux fluxcd/flux command should include this flag to explicitly tells flux to point to the "main" branch of the Git repo; otherwise it still takes "master" as the default.
=> Add "--set git.branch=main" while installing flux

content/beginner/160_advanced-networking/secondary_cidr/configure-cni.md
*Issue #993*
Fixed typo of editing aws-node configmap to aws-node daemonset
=> Correct was-node ConfigMap typo

content/beginner/180_fargate/prerequisites-for-alb.md
Fixed the `kubectl get sa aws-load-balancer-controller ...` command (older sa name and wrong namespace)
=> Fix the "kubectl get sa ..." command

content/beginner/120_network-policies/calico/stars_policy_demo/create_resources.files/backend.yaml, content/beginner/120_network-policies/calico/stars_policy_demo/create_resources.files/client.yaml, content/beginner/120_network-policies/calico/stars_policy_demo/create_resources.files/frontend.yaml, content/beginner/120_network-policies/calico/stars_policy_demo/create_resources.files/management-ui.yaml, content/beginner/120_network-policies/calico/stars_policy_demo/create_resources.md
Updated 120_network-policies to use a Deployment instead of a Replication Controller. It is best practice to use Deployments with replicas in favor of replication controllers.
=> Updated 120_network-policies to use a Deployment instead of a Replication Controller

content/beginner/080_scaling/deploy_hpa.md
Description of changes: The Helm chart for metrics-server is now deprecated and should not be used — "This chart is deprecated and no longer supported." The new recommended method is to use the Kubernetes Metrics Server.
=> Update deploy_hpa.md to use k8s Metrics Server

content/intermediate/230_logging/deploy.files/fluentbit.yaml
Since the master node is not visible to the user in EKS, there is no need for tolerations settings to prevent fluentbit from being deployed to the master node.
The environment variables FLUENT_ELASTICSEARCH_HOST and FLUENT_ELASTICSEARCH_PORT are not used. These are unnecessary because they are defined directly in output-elasticsearch.conf in ConfigMap.
=> Removed unnecessary fields from fluentbit.yaml

content/020_prerequisites/workspace.md
I had issues installing Tensorflow after running several of the modules on Cloud9. The reason behind that failure was the lack of space on the Cloud9 environment.
I copied the script from ECS Workshop, I think is very elegant and simple way to increase the size of the disk until Cloud9 allow to add an additional disk from creation.
=> Option to increase Cloud9 disk size

content/beginner/190_fsx_lustre/_index.md, content/beginner/190_fsx_lustre/cleaning.md, content/beginner/190_fsx_lustre/deploying-services.md, content/beginner/190_fsx_lustre/launching-fsx.md
Adding a new module to setup FSx Lustre CSI for EKS and installs a small app that tests PVC and S3 import/export
=> New module for FSx Lustre setup and PVC test

content/beginner/180_fargate/deploying-fargate.md, content/beginner/180_fargate/ingress.md, content/beginner/180_fargate/prerequisites-for-alb.md, content/beginner/180_fargate/prerequisites.md
#1009 
#1003 
When creating a Fargate only cluster, we need to specify the AWS_REGION and the VPC ID
* Updated the helm charts deployment
* Small update based on linter best practice
* Update the region list
* Added some missing output from commands ran during the lab
Tested on a vanilla eksworkshop EKS cluster (EC2) and on a vanilla Fargate only EKS cluster.
=> Fix fargate

content/advanced/420_kubeflow/inference.md
Added a missing dependency required by the inference_client.py to the install line. Error on my environment was:
File "inference_client.py", line 13, in <module>
import requests
ModuleNotFoundError: No module named 'requests'
=> Missing dependency for inference_client.py

content/intermediate/220_codepipeline/configmap.md
The provided script won't correctly generate the rolearn.(Cause by `:r`), Fix it by adding brackets to ACCOUNT_ID.
N/A
Add curly brackets to ACCOUNT_ID variable to fix this issue.
=> add curly brackets to ACCOUNT_ID variable to get correct rolearn

content/advanced/420_kubeflow/kubeflow.files/inference_client.py
There is an issue running Tensorflow that shows a ver big list of "FutureWarning" deprecations messages that falls out of the scope of our workshop.
The change will suppress those warnings as they might confuse the readers and are out of scope of the workshop.
Source here... https://www.cicoria.com/tensorflow-suppressing-futurewarning-numpy-messages-in-jupyter-notebooks/
=> Suppress FutureWarning messages from TensorFlow

content/030_eksctl/console.md
Fixes #1021
The 'Launch using eksctl' section needs an optional step for configuring console access to cluster objects with the new EKS console.
=> add console credentials instructions during setup

content/beginner/180_fargate/prerequisites-for-alb.md
As referred in eks-charts for [aws-load-balancer-controller](https://github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller#configuration) there is a change in helm variable names for `awsRegion` and `awsVpcID` to `region` and `vpcId` respectively
```
helm upgrade -i aws-load-balancer-controller \
eks/aws-load-balancer-controller \
-n kube-system \
--set clusterName=eksworkshop-eksctl \
--set serviceAccount.create=false \
--set serviceAccount.name=aws-load-balancer-controller \
--set image.tag="${LBC_VERSION}" \
--set region=${AWS_REGION} \
--set vpcId=${VPC_ID}
```
=> Update helm commands for aws-load-balancer-controller

content/030_eksctl/console.md
Fix up s/C9_ID/C9_PID/ in 030_eksctl from #1022 
=> but it's actually called C9_PID

content/020_prerequisites/k8stools.md
Removing the additional "yq" as it caused the yq command to not run properly. 
Before it was equivalent to `yq yq <command> [flags] ...` but now should run as `yq <command> [flags] ...`
=> Fixing yq install

config.toml
Added EKS Networking Workshops to `config.toml` for better discoverability and reach for the networking workshop.
=> added EKS Networking Workshops to config.toml

content/030_eksctl/launcheks.md, content/intermediate/320_eks_upgrades/_index.md, content/intermediate/320_eks_upgrades/theprocess.md, content/intermediate/320_eks_upgrades/upgradeaddons.md, content/intermediate/320_eks_upgrades/upgradeeks.md, content/intermediate/320_eks_upgrades/upgrademng.md
I've added a new chapter that will show how to take this cluster from 1.17 to 1.18 with eksctl. I also added a note to the cluster provisioning step indicating why it is one version behind kind of as a reminder for people to not try to make that current so that we can have this upgrade chapter going forward.
=> Added a new chapter to do a full cluster upgrade

content/advanced/320_servicemesh_with_appmesh/port_to_app_mesh/trigger_sidecar_injection.md
*Description of changes:* Removed a hardcoded pod name and replaced it with a dynamic command to fetch it from the Kubernetes API.
=> Remove hardcoded pod name

content/intermediate/330_app_mesh/install_app_mesh_controller/install_controller.md, content/intermediate/330_app_mesh/port_to_app_mesh/trigger_sidecar_injection.md
This change tightens up the IRSA passages in the intermediate 'Getting Started with App Mesh' module (intermediate/330). First, move to using the more narrowly-scoped controller policy from the project repo. Second, add another IRSA for the app namespace which adds proxy authorization. Since we aren't using a Virtual Gateway nor are we using TLS, we don't need to do this... yet. The documentation says that in the future all resources will need proxy authorization, so we might as well add it now.
That said, I don't think it'll address issue #1056 . I am unable to reproduce any issues, and with the simple steps in the module, it works as expected - the sidecar proxies get their config updates from the controller and everything works as expected. Without being able to reproduce it, I'm at a …
=> tighten up app mesh irsa on intermediate module

content/intermediate/290_argocd/deploy_application.md
This change is needed to avoid errors while looking up the CONTEXT_NAME
While setting the CONTEXT_NAME variable, we need to get the current context and not the first available in the array. This change fixes that by getting the current context. 
=> updated to get `current-context` for CONTEXT_NAME

content/beginner/170_statefulset/testscaling.md
The command issued prior to seeing the output contained `data-mysql-2`, but the document's expected output was `data-mysql-3`.
In following this workshop, the output was `persistentvolumeclaim "data-mysql-2" deleted`
Changed the `3` to a `2` to match what was expected
=> Fix minor error in 170_statefulset expected output

content/intermediate/260_weave_flux/app.files/Dockerfile
Step 1/4 : FROM nginx:mainline-alpine    mainline-alpine: Pulling from library/nginx    toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit    
This update was made to stop Dockerhub pull rate limiting.  ECR will use the Account you are pulling from as the rate limiting factor and will avoid errors during the build in CodeBuild for this lab.
=> Updated Dockerfile to use AWS ECR

content/intermediate/241_pixie/_index.md, content/intermediate/241_pixie/deploy_pixie.md
- Point to Pixie's Open Source website (will stop redirecting to `pixielabs.ai` tomorrow at 5:30 am PST). 
- Clarify that this tutorial uses the 100% free hosted version of Pixie. Self-hosted deploy instructions coming soon.
=> Update Pixie deploy directions

templates/ci-cd-codepipeline.cfn.yml, templates/weave_flux_pipeline.cfn.yml
* Points default docker image to Ubuntu 18.04 - The docker image aws/codebuild/docker:17.09.0 is no longer supported and also results in a build error when launching the template.
* Adds `PrivilegedMode: true` which is a requirement for Docker image builds per the [docs](https://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker.html).
* Updates yarnpk gpg key - See https://github.com/yarnpkg/yarn/issues/7866
=> Update codepipeline and flux labs

content/intermediate/290_argocd/update_application.md
Updated the "deployment.yaml" path in documentation. This was not displaying that may causes problem to readers to follow the steps.
*Issue #, if available:*to 
I have updated the file-path instead of url-path for "ecsdemo-nodejs/kubernetes/deployment.yaml"
=> Update update_application.md for deployment.yaml path missing on page

content/beginner/130_exposing-service/connecting.md
*Issue #, if available:* None
Before:
```
Admin:~/environment $ kubectl -n my-nginx run -i --tty load-generator --env="MyClusterIP=${MyClusterIP}" --image=busybox /bin/sh
kubectl run --generator=deployment/apps.v1 is DEPRECATED and will be removed in a future version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.
If you don't see a command prompt, try pressing enter.
```
After(no longer has a deprecation warning):
```
Admin:~/environment $ kubectl -n my-nginx run  --generator=run-pod/v1 -i --tty load-generator --env="MyClusterIP=${MyClusterIP}" --image=busybox /bin/sh                            
If you don't see a command prompt, try pressing enter.
```
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …
=> Avoid deprecation warning in kubectl run command

content/advanced/330_servicemesh_using_appmesh/add_nodegroup_fargate/_index.md
Currently, the rendered link yield https://www.eksworkshop.com/advanced/330_servicemesh_using_appmesh/add_nodegroup_fargate/020_prerequisites/workspace/#increase-the-disk-size-on-the-cloud9-instance, which is wrong. Prepending / should fix this.
=> Fix link to c9 resize anchor

content/020_prerequisites/k8stools.md
This change is needed in order to successfully run through the [Deploying Microservices to EKS Fargate](https://www.eksworkshop.com/beginner/180_fargate/) module.  Otherwise, you will run into an error as described in issue #1154.
=> Update LBC_VERSION to v2.2.0

content/beginner/160_advanced-networking/secondary_cidr/test_networking.md
Fixes #1158
Updates deprecated `kubectl run` for creating deployments. This currently only results in a warning but will break in later kubectl versions.
=> Deprecate 'kubectl run' for deployment creation

content/advanced/310_servicemesh_with_istio/download.md, content/advanced/310_servicemesh_with_istio/install.md
currently workshop material is using istio version 1.9.0
- update content to use istio version 1.10.0
- replace `istioctl manifest apply` with `istioctl install` in istio installation section
=> update istio version to 1.10.0

content/advanced/310_servicemesh_with_istio/download.md, content/advanced/310_servicemesh_with_istio/install.md, content/advanced/310_servicemesh_with_istio/introduction.md
introduction.md was still showing istio version 1.9.x in advanced->service mesh with istio-> introduction
updated page to reflect istio version 1.10.x
@Jukie
=> Bugfix: replace old version of istio on introduction.md

content/beginner/170_statefulset/statefulset.files/mysql-statefulset.yaml, content/beginner/170_statefulset/statefulset.md, content/beginner/170_statefulset/storageclass.md, content/beginner/170_statefulset/testscaling.md, content/intermediate/230_logging/deploy.files/es_domain.json, content/intermediate/240_monitoring/deploy-grafana.md, content/intermediate/240_monitoring/deploy-prometheus.md, content/intermediate/280_backup-and-restore/backupandrestore.files/storage-class.yaml
Reverting changes as they introduced additional steps in the initial deployment of the cluster as the default storageclass remains gp2, will need to retest most labs before pushing.
=> Revert "170_statefulset lab upgrade all gp2 to gp3"

content/beginner/130_exposing-service/cleaning.md, content/beginner/130_exposing-service/ingress_controller_alb.md
The `Beginner > Exposing a Service > Ingress Controller` sample application does not support Kubernetes Versions 1.19+.    I worked with the kubernetes-sig/aws-load-balancer-controller maintainers to [revert a change](https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/2068) that broke the lab.
In addition, I created a [PR with the kubernetes-sig/aws-load-balancer-controller maintainers](https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/2072) to added support for the new spec in the Ingress resource in Kubernetes version 1.19.
This PR is to update the lab to support the PR in kubernetes-sig/aws-load-balancer-controller.
Tested with this PR with the following Kubernetes Versions:
By submitting this pull request, I confirm that you can use, modify, copy, …
=> Update Ingress Controller lab to support latest sample application

package-lock.json, package.json
https://github.com/aws-samples/eks-workshop/security/dependabot/package-lock.json/normalize-url/open
Pathing some vulnerabilities per dependabot
Dependabot alerts were specific to normalize-url package, which is a transitive dependency of hugo and cacheable-request.
=> Updated vulnerable packages per dependabot alert

content/beginner/115_sg-per-pod/50_deploy.md
Fixed typo in SG section. updated "MAME" to "NAME"
Fixed small typo in variable name. 
Changing MAME to NAME
=> Fixing typo in variable name

content/intermediate/210_jenkins/deploy.md
*Issue #, if available:* https://github.com/aws-samples/eks-workshop/issues/991
*Description of changes:* 
Added compatible Jenkins plugin versions as codecommit jobs plugin is currently in broken state.
Set Jenkins image tag to current latest lts tag
=> jenkins-deploy-workshop: updated jenkins version and plugin versions which are compatible with each other

content/020_prerequisites/clone.md
Migrating ecsdemo-frontend repo to aws-containers org.
=> Moving the frontend repo clone from brentley to aws-containers repo

content/beginner/190_efs/launching-efs.md
Starting with 1.19, Amazon EKS no longer adds the kubernetes.io/cluster/<cluster-name> tag to subnets passed in during cluster creation ([official documentation](https://docs.amazonaws.cn/en_us/eks/latest/userguide/kubernetes-versions.html#kubernetes-1.19)). 
Currently the EFS module in the EKS workshop is broken because when it's trying to find all the public subnets that should be used to create the EFS mount-target, it's trying to do a `aws ec2 describe-subnets --filter <TAGS>` where the `kubernetes.io/cluster/$CLUSTER_NAME` it not anymore available on EKS versions 1.19 and above. 
For a fix, I'm suggesting using the `alpha.eksctl.io/cluster-name` with value `$CLUSTER_NAME` to fix the issue.
I have tested and validated that this works …
=> Bug 🐛  - Fixing missing tag on subnet for EFS module

content/beginner/070_healthchecks/livenessprobe.md
+ The Events in "describe pod" doesn't show "IP Address" any more under "From" column
+ Other cosmetic information is different from the existing content
+ Unhealthy event message c"Liveness probe failed" message is changed to reflect new from 1.19 & 1.20 versions
+ "Killing container with id docker" is not shown in 1.19 & 1.20 versions.  
=> Updated the Events screenshot for describe pod command.

content/beginner/115_sg-per-pod/09_prerequisite.md, content/beginner/115_sg-per-pod/10_secgroup.md, content/beginner/115_sg-per-pod/20_rds.md, content/beginner/115_sg-per-pod/30_cni_config.md, content/beginner/115_sg-per-pod/50_deploy.md, content/beginner/115_sg-per-pod/90_cleanup.md, content/beginner/115_sg-per-pod/_index.md
Updated Lab 115 - "Security Groups for Pods" - Tested with EKS 1.19, 1.20, and 1.21 all created with eksctl. Docs render correctly via Hugo.
Index: Updated wording for clarity and sentence flow
09_Prerequisites:  Updated node selector as the beta selector was deprecated as of k8s 1.17
10_SecurityGroups: Updated wording for clarity
20_RDS: Updated to PostgreSQL12 via Amazon Linux Extras, the old command installed unsupported version 9.2 and the instance created in above command was Engine V12.
30_CNI: Updated selector from alpha.eksctl to standard eks label provided by managed nodegroups
50_Deploy: Fixed output that was not rendering along with other typo
90_Cleanup: Updated to remove PostgreSQL12 as installed in 20_RDS
By submitting …
=> Updated Lab 115 - Pod Security Groups

content/beginner/185_bottlerocket/launchbottlerocket.md
1) Updated to use Kubernetes version dynamically
2) Tested with Kubernetes version 1.19 and 1.20
3) Improved the text to check nodes and nodegroups
=> updated to use K8s version dynamically. tested with 1.19 and 1.20

content/beginner/190_fsx_lustre/deploying-services.md
I tested FSx section for both EKS 1.19 and EKS 1.20. All the up-to-date Kubernetes tools such eksctl, kubectl are fully compatible with steps provided in "Install Kubernetes Tools" 
Changes I submitted are mostly cosmetic. You will see updated dates, a clarification on one of the steps and kubectl command update for exec access to pods.
=> Updates to FSx Section

content/020_prerequisites/workspaceiam.md
There is a struggle finding the correct entry in the settings menu, as well as disabling (turning off) the "AWS managed temporary credentials in the console.
This change propose to use AWS CLI command instead of manual step via screenshot (tested on C9 workspace)
=> Change the IAM setting for the workspace

content/beginner/091_iam-groups/create-k8s-rbac.md
updating role and rolebinding to k8s API version v1 since v1beta1 will be unavailable in k8s v1.22+
=> Role and Rolebinding API version bump v1beta1 to v1

content/advanced/330_servicemesh_using_appmesh/deploy_applications/about_the_k8s_app.md
"Fask" should read "Flask"
Corrected spelling of "Flask"
=> typo in about_the_k8s_app.md

content/beginner/130_exposing-service/ingress_controller_alb.md
Fixes: https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2455
Use the recent release tag for example manifests instead of the main branch. The release tag is stable and immune to recent changes.
=> update 2048 example app manifest url

content/beginner/194_secrets_manager/sync_native_secrets_env.md
As great of a name as Kuberbetes is, I thought I'd fix this typo.
=> typo: s/Kuberbetes/Kubernetes/

content/intermediate/330_app_mesh/port_to_app_mesh/trigger_sidecar_injection.md
Fixes #1056
The `prod-proxies` service account was never redeclared onto the deployment, changing the module to set the IAM permissions to the default service account.
=> Change service account for App Mesh injection to default

content/020_prerequisites/k8stools.md, content/beginner/130_exposing-service/cleaning.md, content/beginner/130_exposing-service/ingress_controller_alb.md, content/beginner/180_fargate/prerequisites-for-alb.md
Changed the content to install AWS Load Balancer Controller v2.4.1 instead of v2.4.0. Before this change, the instructions in "Install Kubernetes Tools" page were referring to v2.4.0, but the instructions in "Ingress Controller" page were referring to v2.3.0. Also, the latest version of the helm chart was used which does not align with v2.4.0 of the AWS Load Balancer Controller. I explicitly specified the version of the helm chart to avoid the re-occurrence of this issue. I also changed the content of the Fargate lab to align with these changes.
=> Upgrade aws lb controller

content/beginner/085_scaling_karpenter/setup_the_environment.md
As of today, the Cluster Name extraction query result in "null" because [0].metadata.name results in the same. 
The JSON has a field called 'Name' which starts with an upperCase N. 
{
"Name": "sample-eksctl",
"Region": "us-west-2",
"Owned": "True"
}
Modified the command  to   [0].Name' that results in the proper extraction.
=> Update Cluster Name extraction query

templates/weave_flux_pipeline.cfn.yml
Removing `sudo` from apt-key line seems to work with the build issue.
#1347
`sudo apt-key add -` was failing, removing sudo allows adding of gpg key which removes any build errors.
=> Updating to remove issues with apt-key

content/beginner/091_iam-groups/test-cluster-access.md
command "kubectl run --generator=run-pod/v1 nginx-dev --image=nginx -n development"
throws an error if the Cloud9 environment has not been cleaned up from a previous lab.
example : if you were doing the "090_rbac" lab and you skipped this steps "https://www.eksworkshop.com/beginner/090_rbac/cleanup/", you would get an error. Often times, a mock environment is set up for short duration so the clean up task is skipped and the audience/trainee is stuck with this error.
=> Update add helpful tip to eliminate error

content/beginner/194_secrets_manager/configure-csi-driver.md
According to https://secrets-store-csi-driver.sigs.k8s.io/getting-started/upgrades.html the helm chart repository URL has changed to https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
=> Change the helm chart repository URL

content/intermediate/300_cis_eks_benchmark/debug-mode.md, content/intermediate/300_cis_eks_benchmark/intro.md, content/intermediate/300_cis_eks_benchmark/run-as-job.md, content/intermediate/300_cis_eks_benchmark/ssh-into-node.md
Issue: Error while trying to run kube-bench with provided instructions
```
$ kube-bench --benchmark eks-1.0
error validating targets: No targets configured for eks-1.0
```
The latest EKS benchmark available in kube-bench is 1.0.1.
I updated the different instructions and config fils to refer to this version. 
=> Kube bench - Update to EKS 1.0.1 benchmark

content/beginner/194_secrets_manager/deploy-workload-secret.md, content/beginner/194_secrets_manager/sync_native_secrets_env.md
Workshop using deprecated version of SecretStoreProvider in K8s 1.21.
Updated to v1 from v1alpha1.
=> fixed deprecated versioning on SecretProviderClass

content/beginner/190_efs/efs-csi-driver.md
changing to kubectl apply -k "github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-1.3"
Source : https://github.com/kubernetes-sigs/aws-efs-csi-driver
=> EFS/CSI driver version for 1.21 and beyond is 1.3

content/intermediate/241_pixie/using_pixie/http_data.md, content/intermediate/270_custom_resource_definition/creating_co.md, content/intermediate/270_custom_resource_definition/creating_crd.md
- Update the API version of CustomResourceDefinition from apiextensions.k8s.io/v1beta1 to apiextensions.k8s.io/v1 as stated in the k8s 1.21 dash docs:
- Added schema openAPIV3Schema to the CRD manifest
- Updated commands outputs to mach with the new API version.
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#customresourcedefinition-v122
=> Update CustomResourceDefinition API version

content/beginner/040_dashboard/dashboard.md
Update dashboard version from v2.0.0 to v2.2.0 as stated in the k8s 1.21 dash docs:
https://v1-21.docs.kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/
=> Update dashboard version

content/beginner/170_statefulset/statefulset.files/mysql-statefulset.yaml
*Issue #, if available:* Fixes #1479
Change `hostname` command in init script to `uname -n`.
=> StatefulSets: Replace `hostname` with `uname -n` in init script

content/intermediate/290_argocd/cleanup.md
Install steps used v2.4.7 manifest.  Updated cleanup steps to match.
=> Update cleanup steps for ArgoCD to match install

content/beginner/060_helm/helm_nginx/installnginx.md
The documentation on this [page](https://www.eksworkshop.com/beginner/060_helm/helm_nginx/installnginx/) says:
- "The first object shown in this output is a Deployment"
- "The next object shown created by the Chart is a Pod"
- "The third object that this Chart creates for us is a Service"
which does not match to the command it executes `kubectl get svc,po,deploy`
Fixed the resource order in the command to avoid confusion.
=> fix: change resource order to match the docs

content/beginner/085_scaling_karpenter/install_karpenter.md
Karpenter is having two containers `controller` and `webhook` instead earlier we said two deployment and pods i.e. karpenter-controller and karpenter-webhook
=> Fix incorrect info about two pods

content/beginner/190_fsx_lustre/launching-fsx.md
Without "fsx:TagResource" pvc stays in Pending state.
=> Add action to policy

content/beginner/080_scaling/test_hpa.md
--generator flag has been deprecated.
```
~/Workspace/Experiments/eksworkshop ❯ kubectl --generator=run-pod/v1 run -i --tty load-generator --image=busybox /bin/sh                 
error: unknown flag: --generator
See 'kubectl run --help' for usage.
```
remove generator flag
```
kubectl run -i --tty load-generator --image=busybox /bin/sh    
```
=> docs: update test_hpa.md to drop --generator flag

content/intermediate/320_eks_upgrades/_index.md
K8s version for upgrades were still reflecting the old lab (1.20 to 1.21)
=> K8s versions were referring to old setup

content/beginner/060_helm/helm_intro/install.md
For folks familiar with disconnected installs, etc.. the word Download kind of implies that perhaps we would mirror/download the actual repo - not simply configuring it to be available.
=> Updated "Download" to "Add"

content/beginner/190_fsx_lustre/launching-fsx.md
There are two SECURITY_GROUP_ID variables in this doc, and obviously the first one is wrong.
=> Remove the wrong SECURITY_GROUP_ID variable 
